<script>var assign_user_id = '<?php echo $this->user_id; ?>';</script>
<link rel='stylesheet' href='<?php echo $this->basePath() ?>/js/fullcalander/demos/cupertino/jquery-ui.min.css' />
<link rel='stylesheet' href='<?php echo $this->cdn() ?>/css/website/schedule.css' />
<script src='<?php echo $this->basePath() ?>/js/fullcalander/lib/jquery-ui.custom.min.js'></script>
<script src='<?php echo $this->basePath() ?>/js/fullcalander/fullcalendar/fullcalendar.js'></script>
<script>
    $(document).ready(function() {
        calendar();
        $('.fc-event-container').css('display', 'block');
        /*$(".fc-week td").click(function() {
            $(".action-drop").hide();
        });*/
		
   $(document).click(function (e) {
    if (!$(e.target).hasClass("fc-event-title") 
        && $(e.target).parents(".action-drop").length === 0) 
    {
        $(".action-drop").hide();
    }
  });

    });
    var cnt = 0;
    function getSpanText() {

    }
    function calendar(type)
    {
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();
        var user_id = '<?php echo $this->user_id; ?>';
        $('#loadding').show();
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->Url('calendarschedule'); ?>',
            data: {type: 'onload', userId: user_id},
            success: function(data) {
                $('#loadding').hide();
                refreshCalendar(data.events);
            }
        });
    }
    var ouputFlag = '';
    function refreshCalendar(events) {
        $('#calendar12').fullCalendar({
            header: {
                left: 'today',
                center: 'prev,title next',
                right: 'month,agendaWeek,agendaDay'
            },
            editable: true,
            droppable: true, // this allows things to be dropped onto the calendar !!!
            drop: function(date, allDay) { // this function is called when something is dropped
                var CurrentDate = new Date();
                var chapter = $.trim($(this).text()).split('-/');
                var titles = chapter[2];
                var lNames = chapter[0].split('.');
                var lName = lNames[1];
                var tabType = chapter[3];
                var user_id = "<?php echo $this->user_id; ?>";
                var uuid =$("#uuid").val();
                var customboard = "<?php echo $this->board_id; ?>";
                //alert(chapter[2]);
                var planmdate = [date.getFullYear(), date.getMonth() + 1, date.getDate()].join('-');

                var dragDate = new Date(date).setHours(0, 0, 0, 0);
                var todayDate = new Date(CurrentDate).setHours(0, 0, 0, 0);

                if (dragDate >= todayDate) {
                    var chapter_id = chapter[2];
                    var response = "exist";//freechapter(chapter_id);
                    if (response == 'exist') {
                        $('.fc-event-container').css('display', 'block');
                        $.ajax({
                            type: 'POST',
                            url: '<?php echo $this->Url('add-lessons'); ?>',
                            data: {date: planmdate, title: titles, endDate: planmdate, type: '1', lName: lName, tabType: tabType, userId: user_id,uuid:uuid,customboardid:customboard},
                            success: function(data) {

                                if (data.output == 0) {
                                    var idHid = $('#hidId' + titles + (data.planDate)).val();
                                    $("#hiddenevents").append('<input type="hidden" name="previousevent' + titles + '' + idHid + '" id="previousevent' + titles + '' + idHid + '" value="' + data.eventId + '"/>');
                                    $('#' + titles + '' + idHid).val(data.eventId);
                                    $('#hidId' + idHid).val(titles);
                                    addSubjectColor();

                                }else {
                                    alert('Chapter Already Scheduled');
                                    $('#calendar12').remove();
                                    $('#inner-cont_rhtst').append('<div id="calendar12"></div>');
                                    $('#tabCloseOpen').val('1');
                                    $('#calendar12').css('width', '565px');
                                    calendar();
                                    return false;
                                }
                            }
                        });
                    }
                    else {
                        //$('.fc-event-container').css('display','none');
                        return false;
                    }

                } else {
                    alert('Invalid Date(s)');
                    return false;
                }
                var originalEventObject = $(this).data('eventObject');
                var copiedEventObject = $.extend({}, originalEventObject);
                copiedEventObject.start = date;
                copiedEventObject.allDay = allDay;
                $('#calendar12').fullCalendar('renderEvent', copiedEventObject, true);
                if ($('#drop-remove').is(':checked')) {
                    $(this).remove();
                }
            },
            events: events
        });
    }

    function addSubjectColor() {
        //    alert("phtml");
        var chapterId = '';
        var viewchapter = $('#viewchapter').val();
        $.ajax({
            type: 'POST',
            url: "<?php echo $this->Url('subject-color'); ?>",
            data: {chapterId: chapterId, currentuser_id:<?php echo $this->user_id; ?>},
            dataType: 'json',
            success: function(data) { //alert(data.subject_class)
                $('.fc-event-inner').each(function() {
                    var ChapterId = ($('#hidId' + $(this).attr('id')).val());
                    var ChapterColor = data.subject_color[ChapterId];
                    var className = $(this).attr('class').split(' ');//alert(className[1]);ms2item
                    if (className[1] == '') //completedColor
                        $(this).css('background-color', ChapterColor + '!important');
                    if (ChapterId == 0 && className[1] != 'overdueColor')
                        $(this).css('background-color', '#A9A9A9 !important');
                    if (className[1] == 'completedColor')
                        $(this).css('background-color', '#2C6085 !important');
                });

                $('.fc-event-start div').each(function() {
                    var ChapterId = ($('#hidId' + $(this).attr('id')).val());
                    var SubjectClass = data.subject_class[ChapterId];
                    if (SubjectClass != null)
                        $('#class' + $(this).attr('id')).prepend(SubjectClass + ' ');
                });
            }
        });
    }
    function open_calendar_view() {
        $('#calendar12').remove();
        $('#inner-cont_rhtst').append('<div id="calendar12"></div>');
        $('#inner-cont_rhtst').css({'margin-left': '300px'});
        $('#calendar12').css('margin-left', '100px');
        $('#calendar12').css('width', '565px');
        //$('#calendar12').width(590);
        $('#tabCloseOpen').val('1');

        $('#calOpen-dropDown').show();
        $('#container-calendar-report').hide();
        calendar();
    }
    function close_calendar_view() {
        $('#calendar12').remove();
        $('#inner-cont_rhtst').append('<div id="calendar12"></div>');
        $('#calendar12').css('margin-left', '0');
        if (navigator.userAgent.indexOf('MSIE 9.0') > 0 || navigator.userAgent.indexOf('MSIE 10.0') > 0)
        {
            $('*#inner-cont_rhtst').css('position', 'relative');
            $('*#inner-cont_rhtst').css('left', '0');

        }
        $('#tabCloseOpen').val('0');
        $('#calOpen-dropDown').hide();
        $('#container-calendar-report').hide();
        calendar();
    }


</script>
<div id="content" class="dashboard-content mainControllerClass" ng-app="app" ng-controller="mainController" >

    <!--<div class="breadscum_Bg" ng-include="'<?php //echo $this->basePath() .'/App/templates/website/breadscumTemplate.html'; ?>'"></div>-->

   <div  class="breadscum_Bg">
   <div class="container">
   <div class="row">
                <div class="breadcrums-container">
         <?php 
           $arrRequest = array();
           $arrRequest['userName'] = $this->userName;
           $arrRequest['page'] = 'container-calendar-monthly';
        ?>
       <ol class="breadcrumbs clearfix">
           <li><a href="#"><?php echo $this->board_name; ?></a></li>
           <li><a href="#"><?php echo $this->class_name; ?> </a></li>
           <li><?php  if($this->userName!=''){echo 'Schedule of '.$this->userName;}?>
               <span id="subjectName"></span><span id="subSubjectName"></span>
           </li>
       </ol>
      </div>
      </div>
      </div>
      </div>
      
    <div class="dashboard-block">
        <div class="container">
            <div class="row">
      
                    <?php //$nurl=$this->navigationarray[0].'-'.$this->navigationarray[1].'-'.$this->navigationarray[2].'-'.$this->navigationarray[3].'-'.$this->navigationarray[4];  ?>


                        <?php if (isset($_GET['studentId']) && $_GET['studentId'] != '') {
                            ?>
                            <span>
                                <a href="<?php echo $this->Url('my-students') ?>">My Students</a>
                            </span>
                        <?php } ?>

                        <?php echo $this->SubjecSchedulerWidget($this->class_id, $this->user_id,$this->board_id); ?>
                
                
                        <!-- <div id="calOpen-dropDown" class="progress-drop-div">
                            <div class="progress-drop">
                                <?php if (count($this->calenderSubjects) != 0) { ?>					
                                    <div class="prg-rhttext">Select your Subject</div>
                                    <div class="mscl_lbl">
                                        <label>
                                            <select name="sub-select" id="sub-select" class="custom-select_scheduler" onchange="getSubjectsCalender(0)">
                                                <?php foreach ($this->calenderSubjects as $subject) { ?>
                                                    <option value="<?php echo $subject->board_class_subject_id; ?>"><?php echo html_entity_decode($subject->subject_name); ?></option>
                                                <?php } ?>
                                            </select>
                                        </label>
                                    </div>
                                    <br/>
                                    <div>&nbsp;</div>
                                    <?php if (count($this->childSubjectDetails) > 2) { ?>
                                        <span id="childSubjects">
                                            <div class="prg-rhttext">Select Title</div> 
                                            <div class="mscl_lbl">
                                                <label>
                                                    <select name="sub-select1" id="sub-select1" class="custom-select_scheduler" onchange="getSubjectsCalender(1)">
                                                        <?php foreach ($this->childSubjectDetails as $childSubjectDetail) { ?>
                                                            <option value="<?php echo $childSubjectDetail->board_class_parent_subject_id; ?>"><?php echo html_entity_decode($childSubjectDetail->parent_subject_name); ?></option>
                                                        <?php } ?>
                                                    </select>
                                                </label>
                                            </div>
                                        </span>
                                    <?php } ?>
                                <?php } ?>
                            </div>
                        </div> -->
                        <!--			<div class="clear"></div>-->
                        
                       
                        <div id="inner-cont_rhtst" class="ProRight_pannel" style="padding:10px;">
                            <span  id="loadding" style="display:none; position:absolute;top:170px;left:40%;background:#FFF;padding: 10px;z-index:100;"  ><img src="<?php echo $this->cdn() ?>/images/website/loadingnew.gif"/></span>
                            <div id='calendar12'></div>
                            <div id="popupresult" style="display:none;"></div>
                        </div>
                        <span id="hiddenevents"></span>
                        <div style='clear:both'></div>

                        <input type="hidden" id="tabCloseOpen" name="tabCloseOpen" value="0"/>
                        <input type="hidden" id="dragCnt" name="dragCnt" value="0"/>
                        <!--Report PopUp-->
                        <div id="reminder_pop1"  style="display:none">
                            <div class="close-img">
                                <a href="javascript:void(0)"><img class="nursery_close" src="<?php echo $this->cdn() ?>/images/website/close_button.png"></a>
                            </div>
                            <div class="reminder_pop_schedule" id="reminder_pop_schedule">
                                <div id="container-calendar-report" class="search-result-cont-schedule"></div>
                            </div>
                        </div>
                        <div class="normals tooltip" id="test" style="display:none">
                            <span id="span_close">Open Chapters List</span>
                            <span id="span_open">Close Chapters List</span>
                        </div>
      
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $(".close-img").click(function() {
            $("#overlay").hide();
            $('#reminder_pop1').hide();
        });
    });
    function calenderActions(type, ids, value1, chapterId, tabType, class_id) { 
        var urll = '';
        if (type == '2') {       
            var pathurl   = "<?php echo $this->URL('website/default', array('controller' => 'index', 'action' => 'dashboard')) ?>";
            var class_ids = (class_id !='' && class_id !='undefined' )?class_id:"<?php echo $this->class_id; ?>";           
            window.location = pathurl +'/'+class_ids+ '#/chapterDetails/' + chapterId;
        } else {
            if (ids == '0') {
                var id = $('#' + chapterId + value1).val();
            } else {
                var id = ids;
            }
            if (type == '1') {
                $('#loadernewc').show();
                urll = '<?php echo $this->Url('calender-operations'); ?>';
            } else if (type == '3') {
                $('#loadernew').show();
                urll = '<?php echo $this->Url('calendarschedule'); ?>';
            }

            $.ajax({
                type: 'POST',
                url: urll,
                data: {type: type, lessionId: id, chapterId: chapterId, subject_id: '<?php echo $this->subjectId; ?>', tabType: tabType, userId: '<?php echo $this->user_id ?>'},
                success: function(data) {
                    if (type == '1') {
                        //alert(value1);
                        $('#completed' + value1).addClass('hideClass');
                        $(".action-drop").hide();
                        $('#loadernewc').hide();
                        $('.fc-event-inner' + value1).removeClass('penddingColor');
                        $('.fc-event-inner' + value1).removeClass('overdueColor');
                        $('.fc-event-inner' + value1).addClass('completedColor');
                        $('#color' + value1).val('completedColor');
                        //$('#calendar12').css('width','565px');
                        window.location.reload();
                        //$('.horizontalBorder').hide();
                        //$('#calendar12').css('width','850px');
                        //$('.fc-last').css('width','75px');
                    }
                    if (type == '3') {
                        $('#loadernew').hide();
                        var tabOpCl = $('#tabCloseOpen').val();
                        if (tabOpCl == '1') {
                            $('#calendar12').remove();
                            $('#inner-cont_rhtst').append('<div id="calendar12"></div>');                            
                            $(".cbp-spmenu-push").hide();    
                            $('#calendar12').html('');    
                            $('#inner-cont_rhtst').css('width','85%');
 
                            refreshCalendar(data.events);
                            $('.horizontalBorder').hide();
                            //addSubjectColor();
                        } else {
                            $('#calendar12').remove();
                            
                            $(".cbp-spmenu-push").hide();    
                            $('#calendar12').html('');    
                            $('#inner-cont_rhtst').css('width','85%');                            
                            $('#inner-cont_rhtst').append('<div id="calendar12"></div>');
                            //$('#calendar12').css('width','565px');
                            $('#calendar12').css('margin-left', '0');
                            if (navigator.userAgent.indexOf('MSIE 9.0') > 0 || navigator.userAgent.indexOf('MSIE 10.0') > 0)
                            {
                                $('*#inner-cont_rhtst').css('position', 'relative');
                                $('*#inner-cont_rhtst').css('left', '0');

                            }
                             $('#inner-cont_rhtst').css('width','85%');
                            refreshCalendar(data.events);
                            $('.horizontalBorder').hide();
                            //addSubjectColor();
                        }

                    }
                }
            });
        }
    }

    function RecalenderActions(type, ids, value1, chapterId, tabType,class_id,customboardId) {
      $('#loadding').css('display','block');  
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->Url('schedulerchapterlist'); ?>',
            data: {type: 'reschdule', lessionId: ids, chapterId: chapterId, subject_id: '<?php echo $this->subjectId ?>', user_id: '<?php echo $this->user_id ?>',customboardid:customboardId},
            success: function(data) {
                $('#calendar12').html('');
                $('#inner-cont_rhtst').css('width','61.8%');
                $('#loadding').css('display','none');
                $('#schedulerchapterlist').html(data);
                calendar();
                //addSubjectColor();
            }
        });

    }
    
   function acceptcalender(type, ids, value1, chapterId, tabType)
   {  
      //For Accept 
      if(type == '1') 
       { 
           var typeset = 'accept';
       }else{
           var typeset = 'decline';
       }
        var pathurl   = "<?php echo $this->URL('notification/default', array('controller' => 'index', 'action' => 'scheduleropration')) ?>";
          $.ajax({
            type: 'POST',
            url: pathurl,
            data: {type: typeset, lessionId: ids, chapterId: chapterId, subject_id: '<?php echo $this->subjectId ?>', user_id: '<?php echo $this->user_id ?>',loggeduser_id:'<?php echo $this->zfcUserIdentity()->getId(); ?>'},
            success: function(data) {
                if(data.output=='0'){
                    calendar();
                }else{
                    alert(data.msg);
                    calendar();
                }
            }
        }); 
   
       
   } 

</script>
<script src="<?php echo $this->basePath() ?>/js/classie.js" language="javascript"></script>
<script src="<?php echo $this->basePath() ?>/js/jquery.menu-aim.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath() ?>/js/menutrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath() ?>/js/menu.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath() ?>/js/responsive-calendar.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".responsive-calendar").responsiveCalendar({
            time: '2013-05',
            events: {
                "2013-04-30": {"number": 5, "badgeClass": "badge-warning", "url": "http://w3widgets.com/responsive-slider"},
                "2013-04-26": {"number": 1, "badgeClass": "badge-warning", "url": "http://w3widgets.com"},
                "2013-05-03": {"number": 1, "badgeClass": "badge-error"},
                "2013-06-12": {}}
        });
    });
</script>
<script type="text/javascript">
    function getSubjectsCalender(type) {
        $('#ajaxLoading').html('<span  id="loadding" ><img src="<?php echo $this->cdn() ?>/images/website/loadingnew.gif"/></span>');
        if (type == '1')
        {
            $("#subSubjectName").html(" > " + $("#sub-select1 option:selected").text());
            var subjectId = $('#sub-select1').val();
            var subjectname = 0;
        } else {
            $("#subjectName").html($("#sub-select option:selected").text());
            $("#subSubjectName").html('');
            var subjectId = $('#sub-select').val();
            var subjectname = $("#sub-select option:selected").text();
        }
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->Url('calendarschedule'); ?>',
            data: {subjectId: subjectId, subjectname: subjectname},
            success: function(data) {
                $('#loadding').hide();
                $('#ajaxChapters').html(data);
            }
        });
        if (subjectname != '0')
        {
            $.ajax({
                type: 'POST',
                url: '<?php //echo $this->Url('child-subjects');    ?>',
                data: {subjectId: subjectId, subjectname: subjectname},
                success: function(subjectdata) {
                    if (subjectdata != '')
                    {
                        $('#childSubjects').show();
                        $('#childSubjects').html(subjectdata);
                    }
                    else {
                        $('#childSubjects').hide();
                    }
                }
            });
        }
    }
    function getCalReport() {
        $.ajax({
            type: 'POST',
            url: '<?php //echo $this->Url('container-calendar-report');    ?>',
            data: {type: 'subReport', board_id: '', class_id: ''},
            success: function(data) {
                //$("#overlay").show();
                $('#reminder_pop1').show();
                $('#container-calendar-report').show();
                $('#container-calendar-report').html(data);
            }
        });
    }
</script>
