<!--- according menu -->
 <link rel="stylesheet" href="<?php echo $this->cdn() ?>/css/jquery-ui.css">
  <link rel="stylesheet" href="<?php echo $this->cdn() ?>/css/component.css">
<script src="<?php echo $this->basePath() ?>/js/jquery-ui.js"></script>
<script src="<?php echo $this->basePath() ?>/js/container.js"></script>
<script src="<?php echo $this->basePath() ?>/js/easyResponsiveTabs.js" type="text/javascript"></script>
<!--- according menu -->
<div id="inner-cont_st">
	<div id="inner-image-show" style="display:none;">
		<img src="<?php echo $this->cdn() ?>/images/slide_open_icon.png"/>
	</div>
	<div id="inner-image-close" style="display:none;">
		<img src="<?php echo $this->cdn() ?>/images/slide_close_icon.png"/>
	</div>
	<div id="inner-cont_lftst">
		<div class="main-bg">
			<div class="main">
				<ul id="responsive_menu">
					<?php if(!isset($_GET['studentId'])){?>
					<?php if(isset($this->chapterdetails) && count($this->chapterdetails)){ ?>
					<li class="subject"><a id="ms1" class="showmnu" href="<?php //echo $this->Url('select-subjects');?>/<?php //echo $this->navigationarray[0]."-".$this->navigationarray[1]."-".html_entity_decode($this->navigationarray[2])."-".$this->navigationarray[3]."-".$this->navigationarray[4]."?chapter=".$this->page_id;?>">
						<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/subject.png" alt="" align="left" title="" border="0" /></p>
						<p align="center" class="leftSideTxt txt1">SUBJECT</p></a></li>
					<?php }else{?>
					<li class="subject"><a class="showmnu" href="<?php echo $this->Url('select-subjects');?>/<?php echo $this->navigationarray[0]."-".$this->navigationarray[1]."-".html_entity_decode($this->navigationarray[2])."-".$this->navigationarray[3];?>">
						<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/subject.png" alt="" align="left" title="" border="0" /></p>
						<p align="center" class="leftSideTxt txt1">SUBJECT</p></a></li>
					<?php }}?>
					<?php if(isset($_GET['studentId']) && $_GET['studentId']!=''){?>
						<li class="schedule">
						<a id="ms2" class="showmnu" href="<?php echo $this->Url('calendarschedule');?>/<?php //echo $this->navigationarray[0]."-".$this->navigationarray[1]."-".html_entity_decode($this->navigationarray[2])."-".$this->navigationarray[3];?>?studentId=<?php echo $_GET['studentId'];?>">
							<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/calendar.png" alt="" align="left" title="" border="0" /></p>
							<p align="center" class="leftSideTxt">Schedule</p> 
						</a>
					</li>
					<?php }else{?>
					<?php if(is_object($this->zfcUserIdentity()->getId())){?>
					<li class="schedule">
						<a id="ms2" class="showmnu" href="<?php echo $this->Url('calendarschedule');?>/<?php //echo $this->navigationarray[0]."-".$this->navigationarray[1]."-".html_entity_decode($this->navigationarray[2])."-".$this->navigationarray[3];?>">
							<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/calendar.png" alt="" align="left" title="" border="0" /></p>
							<p align="center" class="leftSideTxt">Schedule</p> 
						</a>
					</li>
					<?php }else{?>
						<li class="schedule">
						<a class="showmnu fancybox" id="various1" onclick="getPopupForms('login');" href="javascript:void(0)">
							<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/calendar.png" alt="" align="left" title="" border="0" /></p>
							<p align="center" class="leftSideTxt">Schedule</p> 
						</a>
					</li>
					<?php }}?>
					<?php if(isset($_GET['studentId']) && $_GET['studentId']!=''){?>
					<li>
						<a class="showmnu" href="<?php //echo $this->Url('notes');?>/<?php //echo $this->navigationarray[0]."-".$this->navigationarray[1]."-".html_entity_decode($this->navigationarray[2])."-".$this->navigationarray[3];?>?studentId=<?php echo $_GET['studentId'];?>">
							<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/notes.png" alt="" title="" border="0"  align="left" /></p>
							<p align="center" class="leftSideTxt mleft9">notes</p> 
						</a>
					</li>
					<?php }else{?>
					<?php if(is_object($this->zfcUserIdentity()->getId())){?>	
					<li>
						<a class="showmnu" href="<?php //echo $this->Url('notes');?>/<?php echo $this->navigationarray[0]."-".$this->navigationarray[1]."-".html_entity_decode($this->navigationarray[2])."-".$this->navigationarray[3];?>">
							<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/notes.png" alt="" title="" border="0"  align="left" /></p>
							<p align="center" class="leftSideTxt mleft9">notes</p> 
						</a>
					</li>
					<?php }else{?>
					<li>
						<a class="showmnu fancybox" id="various1" onclick="getPopupForms('login');" href="javascript:void(0)" >
							<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/notes.png" alt="" title="" border="0"  align="left" /></p>
							<p align="center" class="leftSideTxt mleft9">notes</p> 
						</a>
					</li>
					<?php }}?>
					<li>
						<?php if(isset($_GET['studentId']) && $_GET['studentId']!=''){?>
						<a class="showmnu" href="<?php //echo $this->Url('container-progress');?>/<?php //echo $this->navigationarray[0]."-".$this->navigationarray[1]."-".html_entity_decode($this->navigationarray[2])."-".$this->navigationarray[3];?>?studentId=<?php echo $_GET['studentId'];?>">
							<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/progress.png" alt="" align="left" title="" border="0" /></p>
							<p align="center" class="leftSideTxt">PROGRESS</p>
						</a>
						<?php }else{?>
						<?php if(is_object($this->zfcUserIdentity()->getId())){?>
						<a class="showmnu" href="<?php //echo $this->Url('container-progress');?>/<?php echo $this->navigationarray[0]."-".$this->navigationarray[1]."-".html_entity_decode($this->navigationarray[2])."-".$this->navigationarray[3];?>">
							<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/progress.png" alt="" align="left" title="" border="0" /></p>
							<p align="center" class="leftSideTxt">PROGRESS</p>
						</a>
						<?php }else{?>
						<a class="showmnu fancybox" id="various1" onclick="getPopupForms('login');" href="javascript:void(0)" >
							<p align="center"><img class="icon1" src="<?php echo $this->cdn() ?>/images/progress.png" alt="" align="left" title="" border="0" /></p>
							<p align="center" class="leftSideTxt">PROGRESS</p>
						</a>
						<?php }}?>
					</li>
				</ul>
			</div>
                    
			<div  class="leftrightSiderbar">
				<div class="topsideright">
				<img src="<?php echo $this->cdn() ?>/images/Container_Select_Subject/sub_link_top_corner_image.png" align="right" width="31" height="7"></div>
				<div class="leftrightbottom">
					<div class="normals tooltip">
						<span id="span_close">Open Chapters List</span>
						<span id="span_open">Close Chapters List</span>
						<a class="opens" href="javascript:void(0);" style="opacity:1;">&nbsp;</a>
					</div>
				</div>
			</div>
		</div>
		<div class="cbp-spmenu-push" style="display:none;"  id="ms1item">
			<div class="cbpTopimg">
				<div class="topbackroundWhite">&nbsp;</div>
				<img align="right" src="<?php echo $this->cdn() ?>/images/Container_Select_Subject/sub_link_top_corner_image.png" />
			</div>
			<div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left">
			<div class="close_mobile">&nbsp;</div>
				<div id="leftsideMenu">
					<div id="cssmenu">
						<ul>
						<?php foreach($this->chapterdetails as $key=>$chapterdetail){
                                                    
                                                    $chapters[$chapterdetail->id]=($key+1)."".html_entity_decode($chapterdetail['chapter_name']);?>
						<?php if(!is_object($this->zfcUserIdentity()->getId())  && ($key+1)!='1'){?>
						<li><a href="#" class="single"><a class="fancybox" id="various1" onclick="getPopupForms('login');" href="javascript:void(0)"><?php echo ($key+1).".   ".html_entity_decode($chapterdetail['chapter_name']);?></a></li>
						
						<?php }else if((is_object($this->zfcUserIdentity()->getId())  && ($key+1)!='1')&& !in_array($chapterdetail['id']."-".$this->navigationarray[0],$usersubjects)){?>
						<li><a href="#" class="single"><a href="javascript:void(0);" onclick="javascript:alert('Please subscribe to relevant package to view content in this chapter')"><?php echo ($key+1).".   ".html_entity_decode($chapterdetail['chapter_name']);?></a></li>
						
						<?php }else{?>
						<li><a href="#" class="single"><a href="<?php //echo $this->Url('select-chapters');?>/<?php //echo $this->navigationarray['0']."-".$this->navigationarray['1']."-".html_entity_decode($this->navigationarray['2'])."-".$this->navigationarray['3']."-".$this->navigationarray['4']."-".$chapterdetail->board_class_subject_chapter_id."?chapter=".($key+1);?>"><?php echo ($key+1).".   ".html_entity_decode($chapterdetail['chapter_name']);?></a></li>
						<?php }}?>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="cbp-spmenu-push" id="ms2item" style="display:none;">
			<div class="cbpTopimg">
				<div class="topbackroundWhite">&nbsp;</div>
				<img align="right" src="<?php echo $this->cdn() ?>/images/Container_Select_Subject/sub_link_top_corner_image.png" />
			</div>
			<div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" >
				<div class="close_mobile">&nbsp;</div>
				<div>
					<div class="horizontalBorder">
						<div class="sch_drag1" id="drag1">
							<div class="sch_drag1_txt">Drag your Lesson here</div>
						</div>
						<span id="ajaxChapters">
						<?php echo $this->partial('notification/index/tabslist.phtml',array('chapterdetails'=>$this->chapterdetails,'testChapterdetails'=>$this->testChapterdetails));?>  
						</span> 
					</div>
				</div> 
			</div>
		</div>
	</div>
</div>
<script>
function myFunction(data,id,chapterId,tabType){ 
	$(".action-drop").hide();
	$('#'+data).show();
	var colorType=$('#color'+data).val();
	var htmlCompleted='';
	var htmlDoitnow='';
	if(colorType=='completedColor' || chapterId==0){
		htmlCompleted="<a href='javascript:void(0);' style='color:#B0B0B0'>Mark as Completed</a>";
		htmlDoitnow="<a href='javascript:void(0);' style='color:#B0B0B0'>Do It Now</a>";
	}else{
		htmlCompleted="<a href='javascript:void(0);'  onclick='calenderActions(1,"+id+",\""+data+"\","+chapterId+",\""+tabType+"\");'>Mark as Completed<span id='loadernewc' style='display:none'><img src='"+'<?php echo $this->basePath();?>'+"/images/loader16.gif'></span></a>";
		htmlDoitnow="<a href='javascript:void(0);'  onclick='calenderActions(2,"+id+",\""+data+"\","+chapterId+",\""+tabType+"\");'>Do It Now</a>";
	}
	$('#'+data).append(
	"<div class='action-drop' id='"+data+"'>"+
		"<ul>"+
			"<li>"+htmlCompleted+
			"</li>"+
			"<li>"+htmlDoitnow+
			"</li>"+
			"<li>"+
				"<a href='javascript:void(0);'  onclick='calenderActions(3,"+id+",\""+data+"\","+chapterId+");'>Delete<span id='loadernew' style='display:none'><img src='"+'<?php echo $this->basePath();?>'+"/images/loader16.gif'></span></a>"+
			"</li>"+
			"<li>"+
				"<a href='javascript:void(0);' onclick='showLeftbar();' id='ms2item' style='display: block;'>Add New Task</a>"+
			"</li>"+
		"</ul>"+
	"<div class='drop-bottom'></div></div>");
}
$(document).mousedown(function (e) {
    var container = $("ul");
    if (container.has(e.target).length === 0) {
        $(".action-drop").hide();
    }
}); 
function goToSubjectPage(rurl){
	alert('Please select a subject');
	window.location='<?php //echo $this->Url('select-subjects');?>'+'/'+rurl;
 }
$(document).ready(function(){
	$("#responsive_menu").height($("#in-container").height()+7);
	$(".leftrightSiderbar").height($("#in-container").height()+7).css('background-color','white');
});
$(window).resize(function(){
	$("#responsive_menu").height($("#in-container").height()+7);
	$(".leftrightSiderbar").height($("#in-container").height()+7).css('background-color','white');
});
 $(".close_mobile").click(function(){
	$(".cbp-spmenu-push").hide();
	$(".normals a").removeClass("close").addClass("opens");
	$("#inner-image-close").css("z-index","1010");
 }); 
 $(".opens").click(function(){
	$("#inner-image-close").css("z-index","0");
 });
 $(".close").click(function(){
	alert("123456");
	$("#inner-image-close").css("z-index","1010");
 }); 
</script>
