<?php  if($this->metadata!=''){
      echo $this->headTitle($this->metadata->meta_tag); 
/*echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')           
            ->appendName('keyword', $this->metadata->meta_keyword)
            ->appendName('description', $this->metadata->meta_description)
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');*/
?>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="keywords" content="<?php echo  $this->metadata->meta_keyword; ?>" />
<meta name="description" content="<?php echo $this->metadata->meta_description ;?>" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<?php			
}
    ?>
	
    
    