<style>
.unsubscribe {
    background-color: #F3F3F3;
    color: #999999;
    cursor: inherit;
}
.chapterMenu ul li a {
    background-color: #FFFFFF;
    color: #333333;
    min-height: 20px;
    padding: 7px 15px 7px 20px;
    text-align: left;
    width: auto;
}
.chapters ul li a {
    color: #333333;
    display: block;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 13px;
    height: auto;
    padding: 7px 5px 7px 20px;
    text-align: left;
    width: auto;
    text-decoration: none;
}
.schedule_input{
    position:relative;line-height:22px;padding:2px 5px;border:1px solid #ccc;color:#9e9e9e;outline:none; margin-left:-6px; margin-top:10px; width:220px;
}
</style>
<?php if(!empty($this->sceduledetail)){
      $lessionname = $this->sceduledetail->lesson_name;
      $startdate   = $this->sceduledetail->plan_date;
      $enddate     = $this->sceduledetail->end_date;
      $startdate   = str_replace('-', '/', $startdate);
      $startdate   = date('d/m/y', strtotime($startdate));
      
      $enddate    = str_replace('-', '/', $enddate);
      $enddate    = date('d/m/y', strtotime($enddate));
      $Re_chepter_id = $this->sceduledetail->package_usage_id;
    }else{
        $lessionname = '';
        $startdate = '';
        $enddate = '';
        $Re_chepter_id = ''; 
    }
    ?>
<div class="sch_drag2" id="drag2">
	<div class="sch_text" id="sch_text">
    	<p id="schd" style="line-height:22px;">SCHEDULE</p>
       <input type="text"  class="schd_task schedule_input" name="schd_task" id="schd_task" size="30"  placeholder="<?php if($lessionname !='') echo $lessionname; else echo "Click or enter an event name";?>"   value="<?php if($lessionname !='') echo $lessionname;?>" />
    </div>
    <div class="sch_text_hrule">&nbsp;</div>
    <div class="sch_left_text"><div class="sch_lftxt_cnt">Start date</div>
        <div class="le">
            <input type='text' id='stdate' class="sch_rttxt_input" value="<?php if($startdate !='') echo $startdate; else echo '';?>"/>
        </div>
    </div>
    <div class="clear"></div>
    <div class="sch_left_text">
        <div class="sch_lftxt_cnt">End date</div>
        <div class="le">
            <input type='text' id='endate' class="sch_rttxt_input" value="<?php if($enddate !='') echo $enddate; else echo '';?>" />
        </div>
    </div>
    <div class="clear"></div>
	<p class="error" id="errorDate"></p>
	<p class="error" id="errorDrag">&nbsp;</p>
    <div class="sch_bt_margin">
        <input type="hidden" name="chapter_details" id="chapter_details" value="" />
        <input type ="hidden" name="scheduleType" id="scheduleType" value="<?php echo (!empty($this->sceduledetail))?"reschedule":""; ?>">
        <input type="hidden" name="uuid" id="uuid"value="<?php echo (!empty($this->sceduledetail->uuid))?$this->sceduledetail->uuid:"";?>"/>
    	<input type="button" value="SCHEDULE" class="sch_btn btn btn-primary" id="btnsch"/>
    </div> 
</div>
<div><!--id="horizontalTab"-->
    <ul class="chapters_tabs">
        <li class="chapters_tab resp-tab-active">CHAPTERS</li>
        <li class="tests_tab">TESTS</li>
   </ul>
   <div class="resp-tabs-container border_top" style="max-height:211px; overflow-y:scroll; overflow-x:visible;" id="ajaxLoading">
   <input type="hidden" name="subjectName" id="subjectName" value="<?php echo $this->subjectName; ?>" />
   <div id="chapterMenu" class="chapters">
     <ul>
       <?php 
           $statusArr = $this->statusArr;
           //echo "<pre />"; print_r($statusArr); exit;
             if(count($chapterdetails)!=0){
               foreach($chapterdetails as $key=>$chapterdetail){
                $keyValue = '';
                $unsubscribeClass = '';                                
           ?>
            <li>
               <a href="#" onclick="fillChapter('<?php echo $key+1 ?>','<?php echo $unsubscribeClass;?>','<?php echo $chapterdetail['chapter_name'];?>','<?php echo $chapterdetail["id"];?>','Chapters');" class="single chapterlist" id="chapterlist<?php $key+1; ?>"><?php echo ($key+1).".   ".$chapterdetail['chapter_name'];?><b style="display:none"><?php echo '-/0';?></b><b style="display:none" class="chapter_ids"><?php echo '-/'.$chapterdetail['id'];?></b><b style="display:none"><?php echo '-/chapters';?></b></a>
            </li>
	  <?php }} ?>
         </ul>
	 </div>
	 <div id="testMenu" class="chapters" style="display:none">
       <ul>
				<?php 
                                    if(count($testChapterdetails)!=0){
                                      foreach($testChapterdetails as $key=>$testChapterdetail){
                                            $unsubscribeClass='';
                                ?>
				<li>
					<a href="#" onclick="fillChapter('<?php echo $key+1 ?>','<?php echo $unsubscribeClass;?>','<?php echo $testChapterdetail['chapter_name'];?>','<?php echo $testChapterdetail["id"];?>','tests');" class="single <?php echo $unsubscribeClass; ?>"><?php echo ($key+1).".   ".$testChapterdetail["chapter_name"];?><b style="display:none"><?php echo '-/0';?></b><b style="display:none"><?php echo '-/'.$testChapterdetail["id"];?></b><b style="display:none"><?php echo '-/tests';?></b></a>
				</li>
				<?php }}else{?>
					<li>
					   <a href="#" class="single"><?php echo 'No Tests'?></a>
					</li>
				<?php } ?>
				</ul>
			</div>
	</div>
</div>
<script>
$(".chapters_tab").click(function() {
	$("#chapterMenu").show();
	$(".chapters_tab").addClass("resp-tab-active");
	$(".tests_tab").removeClass("resp-tab-active");
	$("#testMenu").hide();
});
$(".tests_tab").click(function() {
	$(".chapters_tab").removeClass("resp-tab-active");
	$(".tests_tab").addClass("resp-tab-active");
	$("#chapterMenu").hide();
	$("#testMenu").show();
});
$(document).ready(function() {
	$(".chapters_tab").addClass("resp-tab-active");
	$('.resp-tabs-container li .single').each(function() {
		var eventObject = {
			titleId: $.trim($(this).text()),
			title: $.trim($(this).text())+'-/0'// use the element's text as the event title
		};	
		$(this).data('eventObject', eventObject);
		$(this).draggable({ 
			zIndex: 999,
			revert: true,      // will cause the event to go back to its
			revertDuration: 0  //  original position after the drag
		});
	});
});
$(document).ready(function () {
	$('.resp-tabs-container').easyResponsiveTabs({
		type: 'default', //Types: default, vertical, accordion           
		width: 'auto', //auto or any width like 600px
		fit: true,   // 100% fit in a container
		closed: 'accordion', // Start closed if in accordion view
		activate: function(event) { // Callback function if tab is switched
		var $tab = $(this);
		var $info = $('#tabInfo');
		var $name = $('span', $info);
		$name.text($tab.text());
		$info.show();
		}
	});
	$('#inner-cont_lftst').resize(function(){
		$('#in-container').height($('#inner-cont_lftst').height()+100);
	});
});

function freechapter(chapter_id)
 {
    var chapterId    = $( "ul li b:eq(1)" ).text(); 
        chapterId    = replaceAll('-/','',chapterId);           
    var chapterIds   = $( ".chapter_ids" ).text();
        chapterIds   = replaceAll('-/',',',chapterIds);
    var subject_name = '<?php echo $this->subjectName; ?>';
    var user_id      = '<?php echo $this->user_id; ?>'; 
    var returnValue;
      $.ajax({
		type:'POST',
		url: '<?php echo $this->Url('notification'); ?>/index/freechapter',
		data:{board_class_subject_chapter_id:chapter_id,chapterIds:chapterIds,userId:user_id},
                dataType:'json',
                async: false,
		success: function(data){	 //unsubscribe		
                        if(data.chapterNotExist == 'chapterNotExist'){

                            if(chapter_id == chapterId){
                                //alert('Only first chapter is free.');
                                returnValue = 'exist'; 
                            }
                            $('.chapterlist').addClass('subscribe'); //subscribe
                            $('#chapterlist'+data.key).removeClass('subscribe');
                            $('.chapterlist').addClass('subscribe'); 
                        }
                        if(data.chapterExist == 'chapterExist'){
                           if(data.container_id == chapter_id){                           
                               returnValue = 'exist';
                            }
                           $('.chapterlist').addClass('unsubscribe');
                           $('#chapterlist'+data.key).removeClass('unsubscribe'); 
                    }
                    if(data.package == 'packages'){
                             returnValue = 'exist';
                    }
                }
	});
       //var r = returnValue+'_'+subject_name;
        return returnValue;
 }

function fillChapter(ky,subclass,chapterName,chapterId,type){
    if(subclass != 'unsubscribe'){
        $('#schd_task').val(chapterName);
        $("#schd").html($("#schd_task").val());
        $("#schd_task").hide();
        $("#schd").show();        
        var chapterDetails = ky+'.'+chapterName+'-/'+0+'-/'+chapterId+'-/'+type
        $('#chapter_details').val(chapterDetails);
        
    }else{
        alert('Chapter are not subscribe.');
        $('#schd_task').val('');
        return false;
    }
}

function replaceAll(find, replace, str) {
  return str.replace(new RegExp(find, 'g'), replace);
}

</script>
<script>
$(document).ready(function() {
	var drag_text = '';
	var flag=true;
	MakeStartEndPicker("#stdate", "#endate");
	MakeStartEndPicker("#sstdate", "#eendate");
	$(".ui-datepicker-trigger").css("margin-left",'-22px');
	$(".ui-datepicker").css('width:100px');
	$(".ui-datepicker").css('height:100px');
        //$('.fc-event-inner').css('right','-300px');
	var tasks='';
	var task='';
        
            $('#schd_task').focus(function(){
               $(this).removeAttr('placeholder');
            });
        
	$("#btnsch").click(function() {
		var taskval = $(".sch_text p#schd").html();
		if(taskval =="SCHEDULE"){
                    if($("#schd_task").val()=='Click or enter an event name'){
                            document.getElementById("errorDrag").innerHTML = "Click or enter an event name.";
                            $("#errorDrag").show();
                            $("#schd_task").focus();
                            return false;
                    }
                    if($("#schd_task").val()==''){
		         document.getElementById("errorDrag").innerHTML = "Click or enter an event name.";
			 $("#errorDrag").show();
			 $("#schd_task").focus();
			 return false;
		    }
                        
		}
		if(taskval !=""){
			$("#errorDrag").hide();
		}
		if($("#stdate").val()==''){
			document.getElementById("errorDate").innerHTML = "Select start and end date.";
			$("#errorDate").show();
			return false;
		}
		else if($("#endate").val()==''){
			document.getElementById("errorDate").innerHTML = "Select start and end date.";
			$("#errorDate").show();
			return false;
		}else {
			document.getElementById("errorDate").innerHTML = "";
		}
                
                drag_text = $('#chapter_details').val();//alert(drag_text); 
                if(drag_text == ''){
                    var title = 0;
                    var lName= $('#schd_task').val();
                    tabType = 'custom';
                }else{
                    drag_split = drag_text.split('.');
                    task = drag_split[1];
                    tasks=task.split('-/');
                    
                    var dropchapterId='';
		if(typeof tasks[3]!='undefined'){
			tabType=tasks[3];
		}else{
			tabType='noType';
		}
		if(typeof tasks[2]!='undefined'){
			dropchapterId=tasks[2];
		}else{
			dropchapterId='0';
		}
			var lName='';
			var lessonName=$("#schd").html();
			if(lessonName=='SCHEDULE'){
				lName=$("#schd_task").val();
			}else{
				if(lessonName==''){
					lName=tasks[0];
				}else{
					lName=lessonName;
				}
			}
                        var title=dropchapterId;
                }
                var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
		var startdate = ($("#stdate").val()).split('/');
		var enddate = ($("#endate").val()).split('/');		
			
                var plancdate=$("#stdate").val();
                var endDate=$("#endate").val();
                var cplancdate=new Date(parseInt(plancdate)).setHours(0, 0, 0, 0);
                var cendDate=new Date(parseInt(endDate)).setHours(0, 0, 0, 0);
                var user_id      = '<?php echo $this->user_id; ?>';  
                <?php if(isset($this->lessionid)) { ?>
                     var lesson_id = '<?php echo $this->lessionid; ?>';
                     var paramtype = '<?php echo $this->paramtype; ?>';
                      var uuid =$("#uuid").val();
                <?php }else{ ?>
                    var lesson_id  = '';
                     var paramtype = '';
                     var uuid='';
                <?php } ?>
                 <?php if(!empty($Re_chepter_id)) { ?>
                     if(title == '0'){
                         title = "<?php echo $Re_chepter_id; ?>";
                     }
                     
                    <?php }?>
                         var expdate       = new Date('20'+enddate[2], enddate[1]-1, enddate[0]);
                         var planingdate   = new Date('20'+startdate[2], startdate[1]-1, startdate[0]);
                         var customboardid = "<?php echo $this->customboardId; ?>";
                       if(expdate < planingdate){
                            alert("Start date should be before End date.");
                            return false;
                         }
			if(tabType=='tests' && plancdate!=endDate){
				alert('Tests can be scheduled for a single session only');
			}else{
				$.ajax({
				    type:'POST',
                                    url: '<?php echo $this->Url('add-lessons');?>',
                                    data:{date:plancdate,title:title,endDate:endDate,type:'2',lName:lName,tabType:tabType,userId:user_id,re_less_id:lesson_id,re_paramtype:paramtype,uuid:uuid,customboardid:customboardid},
				    success: function(data){
					if(data.output==0){ 
                                            var idHid=$('#hidId'+title+(data.planDate)).val();
                                            $("#hiddenevents").append('<input type="hidden" name="previousevent'+title+''+idHid+'" id="previousevent'+title+''+idHid+'" value="'+data.eventId+'"/>');
                                            $('#'+title+''+idHid).val(data.eventId);
                                            $('#hidId'+idHid).val(title);
                                            $('#schd_task').val("Click or enter an event name.");
                                            var startDate=new Date('20'+startdate[2], startdate[1]-1, startdate[0]);
                                            ds=('0' + startDate.getDate()).slice(-2);
                                            ms=('0' + (startDate.getMonth()+1)).slice(-2);
                                            ys= startDate.getFullYear();
                                            var startsDate =ys+'-'+ms+'-'+ds;

                                            $('#calendar12').fullCalendar('renderEvent', {
                                            start: new Date('20'+startdate[2], startdate[1]-1, startdate[0]),
                                            end: new Date('20'+enddate[2], enddate[1]-1, enddate[0]),
                                            title: lName+'-/'+data.eventId+'-/'+title+'-/'+'0'+'-/'+data.planDate+'-/'+tabType
                                            }, true);
                                            $('#schd').html('');
                                            $("#stdate").val('');
                                            $("#endate").val('');
                                            $('#chapter_details').val('');
                                            $('#schd').hide();
                                            $("#schd_task").show();
                                            addSubjectColor();
                                        }else if(data.output ==2){
                                            $("#errorDrag").show();
                                            $("#errorDrag").html(data.msg);
                                        } else {
                                            $("#schd_task").val('');
                                            $('#chapter_details').val('');
                                            alert('Chapter Already Scheduled');
						}
					}
				});
			}
	});
});
	function MakeStartEndPicker(startElement, endElement){
        
		$(startElement).datepicker({
			minDate: 0, 
			dateFormat: 'dd/mm/y', 
			showOn: 'button',
			buttonText: 'Show Date',
			buttonImageOnly: true,
			buttonImage: '<?php echo $this->cdn() ?>/images/calender_icon.png',
			duration: 0 ,
			beforeShow: function(input){
                         if($("#scheduleType").val() =='reschedule'){
                                var date2 =  $(endElement).datepicker('getDate');
                                if(date2 != undefined) return { gotoCurrent: date2};
                               }else{
                                 var date2 =  $(endElement).datepicker('getDate');
                                 if(date2 != undefined) return { maxDate: date2 };
                                 }
			}
		});
		$(endElement).datepicker({
			minDate: 0, 
			dateFormat: 'dd/mm/y', 
			showOn: 'button',
			buttonText: 'Show Date',
			buttonImageOnly: true,
			buttonImage: '<?php echo $this->cdn() ?>/images/calender_icon.png',
			
			duration: 0 ,
			beforeShow: function(input)
			{
			var date1 =  $(startElement).datepicker('getDate'); 
			if(date1 != undefined) return { minDate: date1 };
			}
		});
      }
</script>