<script type="text/javascript" src="<?php //echo $this->basePath() ?>/js/libs/em/em_player_factory.js"></script>   
<?php   

foreach ($this->tickers as $ticker) {   
    if ($ticker->ticker_type == 'text') {
        $today = date('Y-m-d');
        ?>
        <!--<marquee style="float:left;width:100%" onmouseover="this.stop();" onmouseout="this.start();">-->
        <?php if ($ticker->start_date <= $today && $ticker->end_date >= $today) { ?>           
            <p class="marqueeText"> <?php echo $ticker->ticker_text; ?> </p>

        <?php } ?>
        <!--</marquee>  -->
         <?php } ?> 
    <?php } ?>
         

