<script type="text/javascript">


    function askques()
    {
        $("#view1").show();
        $("#view2").hide();
        $("#ques").addClass('selected');
        $("#note").removeClass("selected");
        $('#comment_text').focus();
    }

</script>
<?php
if (is_object($this->objauth->getIdentity())) {
    $userType = $this->objauth->getIdentity()->getUserTypeId();

?>
<ul class="rightshow-hidePannel">


    <li class="active notifications"><a href="javascript:void(0);" title="Notification"><img src="<?php echo $this->cdn(); ?>/images/website/services/notification_white-icon.png" alt="" /></a></li>
    <div class="rightshow-hidePannel-showDetail first">
        <?php
        $notificationarray = array();
        echo $this->NotificationWidget($notificationarray);
        ?>	
    </div>

    <?php if (isset($userType) && $userType == '1') { ?>
        <li><a href="javascript:void(0);" title="schedule"><img src="<?php echo $this->cdn(); ?>/images/website/services/schedule_white-icon.png" alt="" /></a></li>
        <div class="rightshow-hidePannel-showDetail">
            <h2>Schedule</h2>
            <ul>
                <?php if (isset($this->userId)) { ?>
                    <li><a id="ms2" class="showmnu" title="My Schedule" href="<?php echo $this->Url('calendarschedule'); ?>/<?php echo @$this->class_id; ?>">My Schedule</a></li>
                <?php } else { ?>
                    <li><a class="showmnu fancybox" title="My Schedule" id="" onclick="getPopupForms('login');" href="javascript:void(0)">My Schedule </a></li>
                <?php } ?>
            </ul>
        </div>

        <li><a href="javascript:void(0);" title="Notes"><img src="<?php echo $this->cdn(); ?>/images/website/services/notes_icon2.png" alt="" /></a></li>
        <div class="rightshow-hidePannel-showDetail">
            <h2>Notes</h2>
            <ul>
                <?php if (isset($this->userId)) { ?>
                    <li><a id="" class="" title="My Notes" href="<?php echo $this->basePath() ?>/notification/index/notes/<?php echo @$this->class_id; ?>">My Notes</a></li>
                <?php } else { ?>
                    <li><a class="showmnu fancybox " title="My Notes" id="" onclick="getPopupForms('login');" href="javascript:void(0)">My Notes</a></li>
                <?php } ?>
            </ul>

        </div>

        <li><a href="javascript:void(0);" title="Mentor"><img src="<?php echo $this->cdn(); ?>/images/website/services/mentor_white-icon.png" alt="" /></a></li>
        <div class="rightshow-hidePannel-showDetail">
            <h2>My Mentor </h2>
            <ul>
                <?php if (isset($this->userId)) { ?>
                    <li> <a id="ms2" class="showmnu" title="Add Mentor" href="<?php echo $this->Url('mymentor'); ?>">Add Mentor</a></li>
                    <li> <a id="ms2" class="showmnu" title="Add Mentor" href="<?php echo $this->Url('mymentor'); ?>">My Mentor</a></li>
                <?php } else { ?>
                    <li> <a class="showmnu fancybox" title="My Mentor" id="" onclick="getPopupForms('login');" href="javascript:void(0)">My Mentor</a></li>
                <?php } ?>
            </ul>	
        </div>

        <li><a href="javascript:void(0);" title="Group"><img src="<?php echo $this->cdn(); ?>/images/website/services/group_white_icon.png" alt="" /></a></li>
        <div class="rightshow-hidePannel-showDetail">
            <h2>Groups</h2>
            <ul>
                <?php if (isset($this->userId)) { ?>
                    <li><a href="<?php echo $this->Url('my-groups') . '/1' ?>" class="" title=" My Groups">My Group Members</a></li>
                    <li><a href="<?php echo $this->Url('my-groups') . '/2' ?>" class="" title=" My Groups">My Membership</a></li>
                    <li><a href="<?php echo $this->Url('my-groups') . '/3' ?>" class="" title=" My Groups" >My Messages</a></li>
                <?php } else { ?>
                    <li><a class="showmnu fancybox" title="My Group Members" id="" onclick="getPopupForms('login');" href="javascript:void(0)" >My Group Members</a> <br>
                    <li><a class="showmnu fancybox" title="My Membership" id="" onclick="getPopupForms('login');" href="javascript:void(0)" >My Membership</a> </li>
                    <li><a class="showmnu fancybox" title="My Messages" id="" onclick="getPopupForms('login');" href="javascript:void(0)" >My Messages</a> </li>
                    <li> <a class="showmnu fancybox" title="My Reports" id="" onclick="getPopupForms('login');" href="javascript:void(0)" >Reports</a> </li>
                <?php } ?>
            </ul>
        </div>

        <li><a href="javascript:void(0);" title="Report"><img src="<?php echo $this->cdn(); ?>/images/website/services/report_white-icon.png" alt="" /></a></li>
        <div class="rightshow-hidePannel-showDetail">
            <h2>Reports</h2>
            <ul>
                <?php if (isset($this->userId)) { ?>
                    <li><a class="showmnu" title="My Reports" href="<?php echo $this->basePath() ?>/report/index/coverage-report#coverage/<?php echo $this->userId; ?>/<?php echo $this->class_id; ?>">Reports</a></li>
                <?php } else { ?>
                    <li><a class="showmnu fancybox" title="My Reports" id="" onclick="getPopupForms('login');" href="javascript:void(0)" >Reports</a></li>
                <?php } ?>
            </ul>	
        </div>
        <?php
    } elseif (isset($userType) && $userType == '2') {
        ?>

        <li><a href="javascript:void(0);" title="mentor"><img src="<?php echo $this->cdn(); ?>/images/website/services/mentor_white-icon.png" alt="" /></a></li>
        <div class="rightshow-hidePannel-showDetail">
            <h2>My Child</h2>
            <ul>
                <?php if (isset($this->userId)) { ?>
                    <li> <a id="ms2" class="showmnu" title="My Child" href="<?php echo $this->Url('myChild'); ?>">Add Child</a></li>
                    <li> <a id="ms2" class="showmnu" title="My Child" href="<?php echo $this->Url('myChild'); ?>">My Child</a></li>
                <?php } else { ?>
                    <li> <a class="showmnu fancybox" title="My Child" id="" onclick="getPopupForms('login');" href="javascript:void(0)">Add Child</a></li>
                <?php } ?>
            </ul>	
        </div>

        <li><a href="javascript:void(0);" title="learner"><img title="My Learner" src="<?php echo $this->cdn(); ?>/images/website/services/learner_white_icon.png" alt="" /></a></li>
        <div class="rightshow-hidePannel-showDetail">
            <h2>My Learner</h2>
            <ul>
                <?php if (isset($this->userId)) { ?>
                    <li> <a id="ms2" class="showmnu" title="Add Students" href="<?php echo $this->Url('my-students'); ?>">Add Students</a></li>
                    <li> <a id="ms2" class="showmnu" title="My Students" href="<?php echo $this->Url('my-students'); ?>">My Students</a></li>
                <?php } else { ?>
                    <li> <a class="showmnu fancybox" title="My Students" id="" onclick="getPopupForms('login');" href="javascript:void(0)">Add Students</a></li>
                <?php } ?>
            </ul>
        </div>
        <?php
    } elseif (isset($userType) && $userType == '3') {
        ?>
        <li><a href="javascript:void(0);" title="Add Child"><img src="<?php echo $this->cdn(); ?>/images/website/services/add-child_white.png" alt="" /></a></li>
        <div class="rightshow-hidePannel-showDetail">
            <h2>My Child</h2>
            <ul>
                <?php if (isset($this->userId)) { ?>
                    <li> <a id="ms2" class="showmnu" title="My Child" href="<?php echo $this->Url('myChild'); ?>">Add Child</a></li>
                    <li> <a id="ms2" class="showmnu" title="My Child" href="<?php echo $this->Url('myChild'); ?>">My Child</a></li>
                <?php } else { ?>
                    <li> <a class="showmnu fancybox" title="My Child" id="" onclick="getPopupForms('login');" href="javascript:void(0)">Add Child</a></li>
                <?php } ?>
            </ul>	
        </div>
        <li><a href="javascript:void(0);" title="Learner"><img src="<?php echo $this->cdn(); ?>/images/website/services/learner_white_icon.png" alt="" /></a></li>
        <div class="rightshow-hidePannel-showDetail">
            <h2>My Learner</h2>
            <ul>
                <?php if (isset($this->userId)) { ?>
                    <li> <a id="ms2" class="showmnu" title="Add Students" href="<?php echo $this->Url('my-students'); ?>">Add Students</a></li>
                    <li> <a id="ms2" class="showmnu" title="My Students" href="<?php echo $this->Url('my-students'); ?>">My Students</a></li>
                <?php } else { ?>
                    <li> <a class="showmnu fancybox" title="My Students" id="" onclick="getPopupForms('login');" href="javascript:void(0)">Add Students</a></li>
                <?php } ?>
            </ul>	
        </div>
        <?php
    }
    ?>
</ul>
<?php } ?>