<?php

namespace Assessment\Model;

/**
 *
 * @author extramarks
 *        
 */
class User {
    // TODO - Insert your code here

    /**
     */ public $user_id;
    public $emailId;
    public $firstName;
    public $boardId;
    public $country_id;
    public $state_id;
    public $classId;
    public $country;
    public $state;
    public $city;
    public $gender;
    public $username;
    public $parent_id;
    public $pakage_id;
    public $package_id;
    public $boardName;
    public $className;
    public $country_name;
    public $state_name;
    public $other_city;
    public $city_name;
    public $nameChild;
    public $subject_name;
    public $syllabus_id;
    public $package_name;
    public $package_type;
    public $order_id;
    public $purchaser_id;
    public $transaction_product_type;
    public $board_name;
    public $class_name;
    public $price;
    public $paid_price;
    public $pkg_payment_details;
    public $pkg_payment_type;
    public $discount_percent;
    public $coupon_code;
    public $discount_type;
    public $address;
    public $display_name;
    public $parent_name;
    public $parent_mobile;
    public $parent_address;
    public $purchase_date;
    public $provider;
    public $user_package_id;
    public $mobile;
    public $school_name;
    public $password;
    public $valid_till;
    public $allowschedule;
    public $payment_mode;
    public $TotalRecords;
    public $name;
    public $login_id;
    public $coupon_type;
    public $payment_source;
    public $currency_type;
    public $create_time;
    public $create_date;
    public $payment_collection_status;
    public $payment_update_user_id;
    public $discount_amount;
    public $offline_tran_id;
    public $transaction_id;
    public $dd_cheque_number;
    public $dd_cheque_date;
    public $deposit_date;
    public $account_number;
    public $bank_branch;
    public $bank;
    public $notes_count;
    public $group_member_count;
    public $schedule_count;
    public $practice_duration;
    public $learn_duration;
    public $total_time;
    public $login_count;
    public $mentor_count;
    public $role_name;
    public $test_attempt_count;
    public $set_status;
    public $ip;
    public $transaction_status;
    public $package_price;
    public $employee_id;
    public $parent_email;
    public $t_parent_id;
    public $child_id;
    public $t_status;
    public $subscription_status;
    public $subscribed_user_type;
    public $subscribe_me;
    public $valid_email;
    public $study_invoice_id;
    public $tab_invoice_id;
    public $coupon_id;
    public $transaction_gateway_response;
    public $combo_class_id;
    public $is_switched;
    public $invoice_id;
    public $sdcard_invoice_id;
    public $login_time;
    public $logout_time;
    public $minimum_selling_price;
    public $tc_minimum_selling_price;
    public $transaction_discount;
    public $transaction_amount;
    public $other_payment_details;
    public $parent_count;
    public $child_count;
    public $learner_count;
    public $is_usd_saved;
    public $is_sgd_saved;
    public $t_parent_child_id;
    public $school_code;
    public $school_id;
    public $package_category;
    public $dob;
    public $transaction_refund_type ;
    public $transaction_total_refund_amount ;
    public $discount;
    public $user_type;
    public $expiry_date;
    public $student_id;
    public $total_package_price;
    public $quantity_ids;
    public $mentor_id;
    public $super_parent_id;
    public $code_assign_id;
    public $assign_activation_code;
    public $assign_card_price;
    public $customBoardName;
    public $customClassName;
    public $customBoardRackId;
    public $custom_board_id;
    public $custom_class_id;
    public $employee_name;
    public $parent_user_type_id;
    public $refered_ids;
    public $chapter_name;
    public $start_time;
    public $end_time;
    public $service;
    public $service_type;
    public $valid_from;
    public $validity_days;
    public $last_login;
    public $repair_replace_id;
    public $repair_replace_status;
    public $request_type;
    public $repair_replace_invoice;

    public function exchangeArray($data) {

        $this->user_id = (isset($data['user_id'])) ? $data['user_id'] : null;
        $this->customBoardName = (isset($data['customBoardName'])) ? $data['customBoardName'] : null;
        $this->customClassName = (isset($data['customClassName'])) ? $data['customClassName'] : null;
        $this->login_id = (isset($data['login_id'])) ? $data['login_id'] : null;
        $this->emailId = (isset($data['email'])) ? $data['email'] : null;
        $this->firstName = (isset($data['display_name'])) ? $data['display_name'] : null;
        $this->lastName = (isset($data['last_name'])) ? $data['last_name'] : null;
        $this->boardId = (isset($data['board_id'])) ? $data['board_id'] : null;
        $this->country_id = (isset($data['country_id'])) ? $data['country_id'] : null;
        $this->state_id  = (isset($data['state_id'])) ? $data['state_id'] : null;
        $this->boardName = (isset($data['board_name'])) ? $data['board_name'] : null;
        $this->classId = (isset($data['class_id'])) ? $data['class_id'] : null;
        $this->className = (isset($data['class_name'])) ? $data['class_name'] : null;
        $this->country = (isset($data['country_name'])) ? $data['country_name'] : null;
        $this->state = (isset($data['state_name'])) ? $data['state_name'] : null;
        $this->city = (isset($data['city'])) ? $data['city'] : null;
        $this->dob = (isset($data['dob'])) ? $data['dob'] : null;
        $this->gender = (isset($data['gender'])) ? $data['gender'] : null;
        $this->mobile = (isset($data['mobile'])) ? $data['mobile'] : null;
        $this->user_type_id = (isset($data['user_type_id'])) ? $data['user_type_id'] : null;
        $this->postalcode = (isset($data['postalcode'])) ? $data['postalcode'] : null;
        $this->user_photo = (isset($data['user_photo'])) ? $data['user_photo'] : null;
        $this->aboutme = (isset($data['aboutme'])) ? $data['aboutme'] : null;
        $this->other_city = (isset($data['city'])) ? $data['city'] : null;
        $this->username = (isset($data['username'])) ? $data['username'] : null;
        $this->parent_id = (isset($data['parent_id'])) ? $data['parent_id'] : null;
        $this->pakage_id = (isset($data['pakage_id'])) ? $data['pakage_id'] : null;
        $this->package_id = (isset($data['package_id'])) ? $data['package_id'] : null;
        $this->country_name = (isset($data['country_name'])) ? $data['country_name'] : null;
        $this->state_name = (isset($data['state_name'])) ? $data['state_name'] : null;
        $this->city_name = (isset($data['city_name'])) ? $data['city_name'] : null;
        $this->nameChild = (isset($data['nameChild'])) ? $data['nameChild'] : null;
        $this->subject_name = (isset($data['subject_name'])) ? $data['subject_name'] : null;
        $this->syllabus_id = (isset($data['syllabus_id'])) ? $data['syllabus_id'] : null;
        $this->package_name = (isset($data['package_name'])) ? $data['package_name'] : null;
        $this->package_type = (isset($data['package_type'])) ? $data['package_type'] : null;
        $this->order_id = (isset($data['order_id'])) ? $data['order_id'] : null;
        $this->purchaser_id = (isset($data['purchaser_id'])) ? $data['purchaser_id'] : null;
        $this->transaction_product_type = (isset($data['transaction_product_type'])) ? $data['transaction_product_type'] : null;
        $this->board_name = (isset($data['board_name'])) ? $data['board_name'] : null;
        $this->class_name = (isset($data['class_name'])) ? $data['class_name'] : null;
        $this->price = (isset($data['price'])) ? $data['price'] : null;
        $this->paid_price = (isset($data['paid_price'])) ? $data['paid_price'] : null;
        $this->pkg_payment_details = (isset($data['pkg_payment_details'])) ? $data['pkg_payment_details'] : null;
        $this->pkg_payment_type = (isset($data['pkg_payment_type'])) ? $data['pkg_payment_type'] : null;
        $this->discount_percent = (isset($data['discount_percent'])) ? $data['discount_percent'] : null;
        $this->coupon_code = (isset($data['coupon_code'])) ? $data['coupon_code'] : null;
        $this->discount_type = (isset($data['discount_type'])) ? $data['discount_type'] : null;
        $this->address = (isset($data['address'])) ? $data['address'] : null;
        $this->display_name = (isset($data['display_name'])) ? $data['display_name'] : null;
        $this->parent_name = (isset($data['parent_name'])) ? $data['parent_name'] : null;
        $this->parent_email = (isset($data['parent_email'])) ? $data['parent_email'] : null;
        $this->parent_mobile = (isset($data['parent_mobile'])) ? $data['parent_mobile'] : null;
        $this->parent_address = (isset($data['parent_address'])) ? $data['parent_address'] : null;
        $this->purchase_date = (isset($data['purchase_date'])) ? $data['purchase_date'] : null;
        $this->provider = (isset($data['provider'])) ? $data['provider'] : null;
        $this->pkg_status = (isset($data['status'])) ? $data['status'] : null;
        $this->user_package_id = (isset($data['user_package_id'])) ? $data['user_package_id'] : null;
        $this->school_name = (isset($data['school_name'])) ? $data['school_name'] : null;
        $this->password = (isset($data['password'])) ? $data['password'] : null;
        $this->valid_till = (isset($data['valid_till'])) ? $data['valid_till'] : null;
        $this->allowschedule = (isset($data['allowschedule'])) ? $data['allowschedule'] : null;
        $this->payment_mode = (isset($data['payment_mode'])) ? $data['payment_mode'] : null;
        $this->login_id = (isset($data['login_id'])) ? $data['login_id'] : null;
        $this->coupon_type = (isset($data['coupon_type'])) ? $data['coupon_type'] : null;
        $this->TotalRecords = (isset($data['TotalRecords'])) ? $data['TotalRecords'] : null;
        $this->name = (isset($data['name'])) ? $data['name'] : null;
        $this->payment_source = (isset($data['payment_source'])) ? $data['payment_source'] : null;
        $this->currency_type = (isset($data['currency_type'])) ? $data['currency_type'] : null;
        $this->create_time = (isset($data['create_time'])) ? $data['create_time'] : null;
        $this->create_date = (isset($data['create_date'])) ? $data['create_date'] : null;
        $this->payment_collection_status = (isset($data['payment_collection_status'])) ? $data['payment_collection_status'] : null;
        $this->payment_update_user_id = (isset($data['payment_update_user_id'])) ? $data['payment_update_user_id'] : null;
        $this->discount_amount = (isset($data['discount_amount'])) ? $data['discount_amount'] : null;
        $this->offline_tran_id = (isset($data['offline_tran_id'])) ? $data['offline_tran_id'] : null;
        $this->transaction_id = (isset($data['transaction_id'])) ? $data['transaction_id'] : null;
        $this->dd_cheque_number = (isset($data['dd_cheque_number'])) ? $data['dd_cheque_number'] : null;
        $this->dd_cheque_date = (isset($data['dd_cheque_date'])) ? $data['dd_cheque_date'] : null;
        $this->deposit_date = (isset($data['deposit_date'])) ? $data['deposit_date'] : null;
        $this->account_number = (isset($data['account_number'])) ? $data['account_number'] : null;
        $this->bank_branch = (isset($data['bank_branch'])) ? $data['bank_branch'] : null;
        $this->bank = (isset($data['bank'])) ? $data['bank'] : null;
        $this->notes_count = (isset($data['notes_count'])) ? $data['notes_count'] : null;
        $this->group_member_count = (isset($data['group_member_count'])) ? $data['group_member_count'] : null;
        $this->schedule_count = (isset($data['schedule_count'])) ? $data['schedule_count'] : null;
        $this->practice_duration = (isset($data['practice_duration'])) ? $data['practice_duration'] : null;
        $this->learn_duration = (isset($data['learn_duration'])) ? $data['learn_duration'] : null;
        $this->total_time = (isset($data['total_time'])) ? $data['total_time'] : null;
        $this->login_count = (isset($data['login_count'])) ? $data['login_count'] : null;
        $this->mentor_count = (isset($data['mentor_count'])) ? $data['mentor_count'] : null;
        $this->role_name = (isset($data['role_name'])) ? $data['role_name'] : null;
        $this->test_attempt_count = (isset($data['test_attempt_count'])) ? $data['test_attempt_count'] : null;
        $this->set_status = (isset($data['set_status'])) ? $data['set_status'] : null;
        $this->ip = (isset($data['ip'])) ? $data['ip'] : null;
        $this->transaction_status = (isset($data['transaction_status'])) ? $data['transaction_status'] : null;
        $this->package_price = (isset($data['package_price'])) ? $data['package_price'] : null;
        $this->employee_id = (isset($data['employee_id'])) ? $data['employee_id'] : null;
        
        $this->t_parent_id = (isset($data['t_parent_id'])) ? $data['t_parent_id'] : null;
        $this->child_id = (isset($data['child_id'])) ? $data['child_id'] : null;
        $this->student_id = (isset($data['student_id'])) ? $data['student_id'] : null;
        $this->t_status = (isset($data['t_status'])) ? $data['t_status'] : null;
        
        $this->subscription_status = (isset($data['subscription_status'])) ? $data['subscription_status'] : null;
        $this->subscribed_user_type = (isset($data['subscribed_user_type'])) ? $data['subscribed_user_type'] : null;
        $this->study_invoice_id = (isset($data['study_invoice_id'])) ? $data['study_invoice_id'] : null;
        $this->tab_invoice_id = (isset($data['tab_invoice_id'])) ? $data['tab_invoice_id'] : null;
        $this->subscribe_me = (isset($data['subscribe_me'])) ? $data['subscribe_me'] : null;
        $this->valid_email = (isset($data['valid_email'])) ? $data['valid_email'] : null;
        $this->coupon_id = (isset($data['coupon_id'])) ? $data['coupon_id'] : null;
        $this->transaction_gateway_response = (isset($data['transaction_gateway_response'])) ? $data['transaction_gateway_response'] : null;
        $this->combo_class_id = (isset($data['combo_class_id'])) ? $data['combo_class_id'] : null;
        $this->is_switched = (isset($data['is_switched'])) ? $data['is_switched'] : null;
        $this->invoice_id = (isset($data['invoice_id'])) ? $data['invoice_id'] : null;
        $this->login_time = (isset($data['login_time'])) ? $data['login_time'] : null;
        $this->logout_time = (isset($data['logout_time'])) ? $data['logout_time'] : null;
        $this->sdcard_invoice_id = (isset($data['sdcard_invoice_id'])) ? $data['sdcard_invoice_id'] : null;
        $this->minimum_selling_price = (isset($data['minimum_selling_price'])) ? $data['minimum_selling_price'] : null;
        $this->tc_minimum_selling_price = (isset($data['tc_minimum_selling_price'])) ? $data['tc_minimum_selling_price'] : null;
        $this->transaction_discount = (isset($data['transaction_discount'])) ? $data['transaction_discount'] : null;
        $this->transaction_amount = (isset($data['transaction_amount'])) ? $data['transaction_amount'] : null;
        $this->other_payment_details = (isset($data['other_payment_details'])) ? $data['other_payment_details'] : null;
        $this->parent_count = (isset($data['parent_count'])) ? $data['parent_count'] : null;
        $this->child_count = (isset($data['child_count'])) ? $data['child_count'] : null;
        $this->learner_count = (isset($data['learner_count'])) ? $data['learner_count'] : null;
        $this->is_usd_saved = (isset($data['is_usd_saved'])) ? $data['is_usd_saved'] : null;
        $this->is_sgd_saved = (isset($data['is_sgd_saved'])) ? $data['is_sgd_saved'] : null;
        $this->t_parent_child_id = (isset($data['id'])) ? $data['id'] : null;
        $this->school_code = (isset($data['school_code'])) ? $data['school_code'] : null;
        $this->school_id = (isset($data['school_id'])) ? $data['school_id'] : null;
        $this->package_category = (isset($data['package_category'])) ? $data['package_category'] : null;
        $this->transaction_refund_type = (isset($data['transaction_refund_type'])) ? $data['transaction_refund_type'] : null;
        $this->transaction_total_refund_amount = (isset($data['transaction_total_refund_amount'])) ? $data['transaction_total_refund_amount'] : null;
        $this->discount = (isset($data['discount'])) ? $data['discount'] : null;
        $this->user_type = (isset($data['user_type'])) ? $data['user_type'] : null;
        $this->expiry_date = (isset($data['expiry_date'])) ? $data['expiry_date'] : null;
        $this->total_package_price = (isset($data['total_package_price'])) ? $data['total_package_price'] : null;
        $this->quantity_ids = (isset($data['quantity_ids'])) ? $data['quantity_ids'] : null;
        $this->mentor_id = (isset($data['mentor_id'])) ? $data['mentor_id'] : null;
        $this->super_parent_id = (isset($data['super_parent_id'])) ? $data['super_parent_id'] : null;
        $this->code_assign_id = (isset($data['code_assign_id'])) ? $data['code_assign_id'] : null;
        $this->assign_activation_code = (isset($data['assign_activation_code'])) ? $data['assign_activation_code'] : null;
        $this->assign_card_price = (isset($data['assign_card_price'])) ? $data['assign_card_price'] : null;
        $this->customBoardRackId = (isset($data['custom_board_rack_id'])) ? $data['custom_board_rack_id'] : null;
        $this->custom_board_id = (isset($data['custom_board_id'])) ? $data['custom_board_id'] : null;
        $this->custom_class_id = (isset($data['custom_class_id'])) ? $data['custom_class_id'] : null;
        $this->employee_name = (isset($data['employee_name'])) ? $data['employee_name'] : null;
        $this->parent_user_type_id = (isset($data['parent_user_type_id'])) ? $data['parent_user_type_id'] : null;
        $this->refered_ids = (isset($data['refered_ids'])) ? $data['refered_ids'] : null;
        $this->chapter_name = (isset($data['chapter_name'])) ? $data['chapter_name'] : null;
        $this->start_time = (isset($data['start_time'])) ? $data['start_time'] : null;
        $this->end_time = (isset($data['end_time'])) ? $data['end_time'] : null;
        $this->service = (isset($data['service'])) ? $data['service'] : null;
        $this->service_type = (isset($data['service_type'])) ? $data['service_type'] : null;
        $this->valid_from = (isset($data['valid_from'])) ? $data['valid_from'] : null;
        $this->validity_days = (isset($data['validity_days'])) ? $data['validity_days'] : null;
        $this->last_login = (isset($data['last_login'])) ? $data['last_login'] : null;
        $this->repair_replace_status = (isset($data['repair_replace_status'])) ? $data['repair_replace_status'] : null;
        $this->repair_replace_id = (isset($data['repair_replace_id'])) ? $data['repair_replace_id'] : null;
        $this->request_type = (isset($data['request_type'])) ? $data['request_type'] : null;
        $this->repair_replace_invoice = (isset($data['invoice_number'])) ? $data['invoice_number'] : null;
    }

    // Add the following method:
    public function getArrayCopy() {
        return get_object_vars($this);
    }

}

