<div id="bannerContainer">
	<div class="aboutusContainer">
		
		<div class="error404-heading">404 <span style="font-size:40px;">error</span></div>
		<div class="error404-contentheading">Page Not Found <img src="<?php echo $this->cdn() ?>/images/search-icon.png" /></div>
		<p class="error404-content">The requested URL could not be matched by routing.<br><p>
       
		
		<div class="clear">&nbsp;</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	 $(".nav-collapse li#about_us").addClass("active");
});
</script>