<?php if ($this->pageCount): ?>
    <div class="zendpagination pagination-centered">
        <ul>
<!--            <li <?php //echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php //echo $this->url('album', array('page' => $this->first, 'order_by' => $order_by, 'order' => $order,)); ?>">&laquo;</a></li>-->
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="javascript:void(0)" onclick="return getnextpage('<?php echo $this->previous ?>')">Previous</a></li>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="javascript:void(0)" onclick="return getnextpage('<?php echo $page ?>')">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>
            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="javascript:void(0)" onclick="return getnextpage('<?php echo $this->next ?>')" >Next</a></li>
            <!-- Last page link -->
<!--            <li <?php //echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php //echo $this->url('album', array( 'page' => $this->last, 'order_by' => $order_by, 'order' => $order,)); ?>">&raquo;</a></li>-->
        </ul>
    </div>
<?php endif; ?>

