<section class="topbar">
    <ul class="container-fluid top-menu">
        <li class="col-md-4">

        </li>
        <li class="col-md-4 text-center">
            <a href="/" class="brand logo">LOGO here</a>
        </li>
        <li class="col-md-4 text-right">
            <a href="javascript:;" data-toggle="modal" data-target="#myModal">Login / </a><a href="javascript:;" data-toggle="modal" data-target="#registrationModal">Register</a>
        </li>
    </ul>
</section>