<?php echo $this->doctype(); ?>
<head>
    <meta charset="utf-8">

    <?php //echo $this->MetaTagsWidget(); ?>
    <?php //echo $this->UserTrackerWidget(); ?>
    <?php
    $this->basePath = $this->basePath();
    ?>
    <!-- Le styles -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->cdn() . '/images/favicon.ico'))
            ->appendStylesheet($this->basePath . '/css/style.css')
            ->appendStylesheet($this->basePath . '/css/bootstrap.css')
            ->appendStylesheet($this->basePath . '/css/jquery.fullPage.css');
    ?>
    <!-- Scripts -->
    <script>
        var BASE_URL = "<?php echo $this->basePath; ?>";
        var notesUrl = BASE_URL;
        var commentsUrl = BASE_URL;
    </script>
    <?php
    echo $this->headScript()
            ->appendFile($this->basePath . '/js/jquery-1.11.3.min.js')
            ->appendFile($this->basePath . '/js/bootstrap.js')
            ->appendFile($this->basePath . '/js/jquery.fullPage.js')
    ;
    ?>
</head>
<body>
    <?php
    echo $this->render('layout/leftbar.phtml');
    ?>
    <section class="wrapper">
        <?php
        echo $this->render('layout/header.phtml');
        echo $this->content;
        ?>
    </section>
    <?php
    echo $this->render('layout/footer.phtml');
    ?>
    <!-- Login Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Login</h4>
                </div>
                <div class="modal-body">
                    <form >
                        <div class="form-group">
                            <label for="username">Email address</label>
                            <input type="text" id="username" name="username" class="form-control" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="text" id="password" name="password" class="form-control" placeholder="password">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Registration Modal -->
    <div class="modal fade" id="registrationModal" tabindex="-1" role="dialog" aria-labelledby="registrationModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Registration</h4>
                </div>
                <div class="modal-body">
                    <?php echo $this->zfcUserRegisterWidget(); ?>
<!--                    <form >
                        <div class="form-group">
                            <input type="text" id="username" name="username" class="form-control" placeholder="First Name">
                        </div>
                        <div class="form-group">
                            <input type="text" id="password" name="password" class="form-control" placeholder="Last Name">
                        </div>
                        <div class="form-group">
                            <input type="text" id="password" name="password" class="form-control" placeholder="Email Address">
                        </div>
                        <div class="form-group">
                            <input type="text" id="password" name="password" class="form-control" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <div class="checkbox">
                                <label>
                                    <input type="radio" name="gender" value="male"> Male
                                </label>
                                <label>
                                    <input type="radio" name="gender" value="male"> Female
                                </label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>-->
                </div>
            </div>
        </div>
    </div>
    
    <script type="text/javascript">
        $(document).ready(function() {
            $('#fullpage').fullpage();
        });
    </script>
</body>
</html>
