<nav class="leftMenu" id="leftMenu">
    <ul class="list-group">
        <li><!-- Things Around me -->
            <a href="#things-around-me">
                <i class="glyphicon glyphicon-check left-icon valign-middle"></i>
            </a>
        </li>
        <li><!-- Women -->
            <a href="#women">
                <i class="glyphicon glyphicon-user left-icon valign-middle"></i>
            </a>
        </li>
        <li><!-- Mens -->
            <a href="#men">
                <i class="glyphicon glyphicon-user left-icon valign-middle"></i>
            </a>
        </li>
        <li><!-- Kids -->
            <a href="#kids">
                <i class="glyphicon glyphicon-user left-icon valign-middle"></i>
            </a>
        </li>
        <li><!-- HOME Decor -->
            <a href="#home-decor">
                <i class="glyphicon glyphicon-home left-icon valign-middle"></i>
            </a>
        </li>
        <li><!-- Beauty & Make up -->
            <a href="#beauty-and-makeup">
                <i class="glyphicon glyphicon-eye-open left-icon valign-middle"></i>
            </a>
        </li>
        <li><!-- Mobile cover and accessories -->
            <a href="#mobile-cover-and-accessories">
                <i class="glyphicon glyphicon-phone left-icon valign-middle"></i>
            </a>
        </li>
        <li><!-- Stationary and office supplies -->
            <a href="#stationary-and-office-supplies">
                <i class="glyphicon glyphicon-tasks left-icon valign-middle"></i>
            </a>
        </li>
    </ul>
</nav>