<div class="modal-dialog" role="document">
<div class="modal-content" >
<div class="modal-header">
        <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span></button>
        <h2 class="popus-title" style="margin: 0;">Answer</h2>
      </div>
<div class="modal-body">
<?php 
 $answerlist = $this->questionAnswer;
 echo html_entity_decode(stripslashes($answerlist[0]->answer));
 
 ?>   
</div>
</div></div>