<?php if($this->zfcUserIdentity()){ ?>
	<link href="<?php echo $this->cdn(); ?>/css/website/bootstrap.css" rel="stylesheet" type="text/css" media="screen" />
	<link href="<?php echo $this->cdn(); ?>/css/extramark.css" rel="stylesheet" type="text/css" media="screen" />
	
<style type="text/css">
body{ padding: 15px 0; margin: 0; font-family: 'Open Sans', sans-serif; background: #fff}
.mcq-view{ font-family: 'Open Sans', sans-serif;}
.Left_Side p{ float: left; margin: 0; width: 70%}
#in-container{ border-radius: 8px; -webkit-border-radius: 8px; -moz-border-radius: 8px; -o-border-radius: 8px;}	
ul.resp-tabs-list, p{
font-size:13px;
}
.singleview-res-cntr-child{ display: table; width: 100%}
.singleview-res-cntr-child{ width: 100%}
</style>
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
$(function()
{
   // for closing the window after form is submitted
   var pagesubmit = '<?php echo $pageSubmit; ?>';
   if(pagesubmit == 'yes')
   {
       window.opener.location.href= '<?php echo $this->Url('mypaper')?>';
       window.close();  
   }
    $("#submitButton").click(function(){
        var paperMarks = '<?php echo $paperMarks; ?>'
        if($('#totmarks').val() == '')
        {
             alert('Aggregate marks cannot be blank.');    
             return false;
        }
       else  if(!$('#totmarks').val().match(/^\d+$/))
        {
             alert('Aggregate marks should be numeric.');
             return false;
        }
        else if(parseInt($('#totmarks').val()) > parseInt(paperMarks))
        {
            alert('Aggregate marks cannot be greater than paper marks.'); 
            $('#totmarks').val() == '';
            return false;
        }
        else
        { 
             $("#mentorevaluatedtest").submit();        
        }        
    });
});
function calTotMarks(inputId, marks, maxmarks)
{ 
        if(!marks.match(/^\d+$/))
        {
            alert("Marks should be numeric.");
            $('#'+inputId).val('');
            return false;    
        }
        else
        {
                if(parseInt(marks) > parseInt(maxmarks))
                {
                     alert('Marks cannot be more than the maximum marks.');  
                     $('#'+inputId).val('');
                     return false;   
                }
                else
                {
                    var totMarks = $('#totmarks').val();
                    var newtotMarks = parseInt(parseInt(totMarks)+parseInt(marks));
                    $('#totmarks').val('');
                    $('#totmarks').val(parseInt(newtotMarks));
                }
        }
}

function deleteTotMarks(marks)
{
        if(marks != '')
        {
                var totMarks = $('#totmarks').val();
                var newtotMarks = parseInt(parseInt(totMarks)-parseInt(marks));
                $('#totmarks').val('');
                $('#totmarks').val(parseInt(newtotMarks));  
        }
}
</script>
<style type="text/css">
.mcqTable td p{
        font-size:14px;
}
</style>

<form method="post" action="<?php echo $this->url('mentortestevaluate', array(), NULL, TRUE);?>" name="mentorevaluatedtest" id="mentorevaluatedtest">
<input type="hidden" name="source" id="source" value="<?php echo $paperSource; ?>" />
<div class="mcq-view mcq-review" style="margin-top:0px;">
            <div class="mcq-title" style="text-align:center">
               <div><?php echo $paperName; ?></div>
			  <div>(<?php echo $paperClass.' - '.$paperSubject; ?>)</div>
			  <div>Marks: <?php echo $paperMarks; ?></div>
                         <?php if($paperTime != '00:00'){?> <div>Time: <?php echo $paperTime.' (hh:mm)'; ?></div><?php } ?>
              <div class="clear">&nbsp;</div>
            </div>
            
            <div class="singleview-res-cntr">
              <span>
			<div style="padding:10px 10px; font-size:14px;"><span style="color:#2C6085; font-weight:bold;"><img style="vertical-align:middle" src="<?php echo $this->cdn(); ?>/images/website/packages//next.png" height="13px" /> Instruction</span> : <?php echo $paperInstruction; ?></div>
              <div class="singleview-res-cntr-child">
                <div class="singleview-res-cntr-left">
                
                <?php 
                if($paperSource == 'add')
                { 
                
                $x=1; 
                foreach($paperQuestionAnswer as $questions)
                {
                ?>
                 <div id="lms">
                        <table class="mcqTable">
                        
                        <tr>
                          <td align="left" width="10%"><strong style="font-size:16px;">Ques <?php echo $x; $x++; ?>.</strong></td>
                          <td align="left" width="80%" style="font-size:16px;" class="Left_Side"><?php echo html_entity_decode(stripslashes($questions['question']));?> <span style="float:right;">(Marks : <?php echo $questions['questionMarks']; ?>)</span></td> 
                        </tr>
                         <tr>
                          <td align="left" width="10%"><strong>Ans.</strong></td>
                          <td align="left" width="80%">
                         <?php echo html_entity_decode(stripslashes($questions['answer']));?> 
                          </td> 
                        </tr>
                         <tr>
                          <td align="left" width="10%"><strong>Marks</strong></td>
                          <td align="left" width="80%"><input type="text" name="ques[<?php echo $paperAssignId?>_<?php echo $questions['paperuseransId']; ?>][marks]" class="marks" id="<?php echo $questions['paperuseransId']; ?>" onfocus="deleteTotMarks(this.value);" onblur="calTotMarks(this.id, this.value, '<?php echo $questions['questionMarks']; ?>')" /></td> 
                        </tr>
                        <tr>
                          <td align="left" width="10%"><strong>Observations</strong></td>
                          <td align="left" width="80%"><textarea name="ques[<?php echo $paperAssignId?>_<?php echo $questions['paperuseransId']; ?>][comments]" cols="" rows="" class="self_textarea"></textarea></td> 
                        </tr>
                        
                        </table>
                </div>
              <?php } } else if($paperSource == 'upload') { ?>
               <div id="lms">
                        <table class="mcqTable">
                        <?php 
                        $q=0;
                        $a=0;
                        foreach($paperQuestionAnswer as $questions)
                        {
                            //$file_path = "http://10.1.9.99/uploads/mentorquestionfiles/".$questions->paperUploadFileName;
                        ?>
                        <?php if($questions->paperUploadFileType == 'ques')
                          { ?>
                        <tr>
                          <td align="left" width="10%"><strong> <?php if($q == 0){ ?> Question: <?php } else {?>&nbsp; <?php }?> </strong></td>
                          <td align="left" width="80%">
                          
                          <a href="<?php echo $this->url('downloadquestion');?>/<?php echo $questions->paperUploadFileName; ?>">Download Question File</a>
                          <span style="float:right;">(Marks : <?php echo $questions->paperUploadFileMarks; ?>)</span>
                          </td> 
                        </tr>
                        <?php $q++; } ?>
                    <?php if($questions->paperUploadFileType == 'ans') { ?>
                         <tr>
                          <td align="left" width="10%"><strong><?php if($a == 0){ ?> Answer: <?php } else {?>&nbsp; <?php }?></strong></td>
                          <td align="left" width="80%">
                          
                          <a href="<?php echo $this->url('downloadquestion');?>/<?php echo $questions->paperUploadFileName; ?>">Download Answer File</a>
                          
                          </td> 
                        </tr>
                        <?php $a++; } } ?>
                        
                        
                        </table>
                </div>
              <?php }?>
                  <table class="mcqTable">
                        
                         <tr>
                          <td align="left"><strong>Aggregate marks</strong></td>
                          <td align="left"><input type="text" name="totalMarks" class="marks" id="totmarks" value="0" <?php if($paperSource != 'upload'){?> readonly <?php } ?> /></td> 
                        </tr>
                        <tr>
                          <td align="left" width="15%"><strong>OverAll Remarks</strong></td>
                          <td align="left" width="75%"><textarea name="mentor_paper_evaluated_comment" cols="30" rows="3" class="self_textarea"></textarea></td> 
                        </tr>
                        
                        
                        </table>
                  <div style="clear:both;"></div>

                </div>
                
              </div>
              
            </div>
            <div class="clear">&nbsp;</div>
             <div class="footer_btn"><input type="button" class="commanBtn" id="submitButton" name="submitButton" value="Submit"></div>
          </div>
       </form>

<?php }else{ ?>
	<script>
		window.location="<? echo $this->url('home');?>"
	</script>
<?php } ?>
