<?php if(count($this->getreply)>0){?>
<?php  $replyanswers=array();foreach($this->getreply as $replyanswer){ $replyanswers=$replyanswer;
$day='';
if($replyanswers->reply_date!=''){
$loggeddate=$replyanswers->reply_date;
$timestamp = explode(" ",$loggeddate);
$date = explode('-', $timestamp[0]);
$year=$date[0];	
$month=$date[1];
$day=$date[2];
$mnth='';
if($month=='1'){$mnth='Jan';}else if($month=='2'){$mnth='Feb';}else if($month=='3'){$mnth='Mar';}
else if($month=='4'){$mnth='Apr';}else if($month=='5'){$mnth='May';}else if($month=='6'){$mnth='Jun';}
else if($month=='7'){$mnth='Jul';}else if($month=='8'){$mnth='Aug';}else if($month=='9'){$mnth='Sep';}
else if($month=='10'){$mnth='Oct';}else if($month=='11'){$mnth='Nov';}else if($month=='12'){$mnth='Dec';}
}?>



<div class="groupact_popcont<?php  echo $replyanswer->userid; ?>" style="display: none;">
       
       <ul class="userprofile_list">
     <li>
       <figure>
                <?php if ($replyanswer->user_photo != '') { ?>
                <img src="<?php echo $this->basePath() ?>/uploads/profileimages/<?php echo $replyanswer->user_photo; ?>" width="90" />
                <?php }else{?>
                <img src="<?php echo $this->cdn() ?>/images/website/guest-avatar.png" width="90" />
                <?php } ?>            
          </figure>
         <span><strong> <?php echo $replyanswer->name; ?>     </strong>    </span>
      </li>
       <li>
          <strong>Board:</strong>
          <span><?php if($replyanswer->board_name!=''){echo $replyanswer->board_name;}else{echo "NA"; }  ?> </span>
       </li>
       <li>
          <strong>Class:</strong>
          <span><?php if($replyanswer->class_name!=''){echo $replyanswer->class_name;;}else{echo "NA"; }  ?></span>
       </li>
       <li>
          <strong>School:</strong>
          <span><?php if($replyanswer->school_name!=''){echo $replyanswer->school_name;;}else{echo "NA"; }  ?></span>
       </li>
       <li>
          <strong>Email:</strong>
          <span><?php if($replyanswer->email_id!=''){echo $replyanswer->email_id;}else{echo "NA"; }  ?></span>
       </li>
        <li>
          <strong>Phone:</strong>
          <span><?php if($replyanswer->mobile!=''){echo $replyanswer->mobile;}else{echo "NA"; }  ?></span>
       </li>
        <li>
          <strong>Location:</strong>
          <span><?php if($replyanswer->address!=''){echo $replyanswer->address;}else{echo "NA"; }  ?></span>
       </li>
       
       </ul>
       
        </div> 



<div class="cmnt-slave">
    <div class="cmnt-table cmnt-table-bot">
<div class="cmnt-row">
   <div class="cmnt-cell" style="text-align: left; padding-left:10px; width: 50%; ">
				Posted by: <b><?php  echo ucfirst($replyanswer->first_name);?></b>(<?php  echo ucfirst($replyanswer->name);?>)
			</div>
			<div class="cmnt-cell" style="text-align: left; padding-left:10px; width: 50%; ">
				Posted Date:<b><?php  echo $day;?>&nbsp;&nbsp;<?php  echo $mnth;?>&nbsp;&nbsp;<?php  echo $year;?></b>
			</div> 
    
    

</div>
</div>
<div class="cmnt-table">
<div class="cmnt-row">
<div class="cmnt-cell cmnt-cell-img">

<?php  if(isset($replyanswers->user_photo) && $replyanswers->user_photo!=""){?>
	<a href="javascript:void(0)" onclick="getUserdata('<?php  echo $replyanswer->user_id;?>')" data-toggle="modal" data-target="#myprofile" data-whatever="@mdo" ><img src="<?php  echo $this->basePath() ?>/uploads/profileimages/<?php  echo $replyanswers->user_photo;?>" width="90" /></a>
<?php }else{?>
	<a href="javascript:void(0)" onclick="getUserdata('<?php  echo $replyanswer->user_id;?>')" data-toggle="modal" data-target="#myprofile" data-whatever="@mdo" ><img src="<?php  echo $this->basePath() ?>/images/avatar_100_1x.png" width="90"/></a>
<?php }?>
</div>
    
    <?php  if($replyanswer->reply_status == '2'){ ?>
      This reply was deleted by <?php  echo $replyanswer->deleted_user;?>
    <?php }else{?>
      <div class="cmnt-cell cmnt-cell-left" style="margin-bottom:10px; display: block; text-align: center; padding-left: 10px;">
<?php  echo $replyanswer->reply_message;?>
          <a style="float: right; margin-right: 10px;" title="Delete" href="javascript:void(0);"  class="remove-link" onclick="changequestionanswerstatus('<?php  echo $replyanswer->reply_id ?>', '2',<?php echo $replyanswer->reply_on_question ?>)"><img width="15" height="15" border="0" src="<?php  echo $this->basePath() ?>/images/website/delete-icon.png"></a>
     <p style="margin-top: 10px;"><a href="javascript:void(0)" onclick="downloadfile('<?php echo $replyanswer->pdf_file_name; ?>','<?php echo $replyanswer->up_down_id; ?>')" title="downloads this file"><?php  echo ($replyanswer->file_name !='')?$replyanswer->file_name:$replyanswer->pdf_file_name; ?></a>
    </p>
         <?php }?>	
</div>
</div>
</div>

</div>
<?php }}else{?>
	There are no comments or answers.	
<?php }?>

<script type="text/javascript">
 function changequestionanswerstatus(Id, Status,quesId)
    {   
        var replyId = Id;
        var replyStatus = Status;
        var quesId = quesId;
       
        if(confirm('Are you sure you want to Delete?')){
            $.ajax({
                type: 'POST',
                url: '<?php  echo $this->Url('changequestionreplystatus'); ?>',
                data: {replyId: replyId, replyStatus: replyStatus},
                dataType:"json",
                success: function(data) {
                    $('#loaddingActivity').hide();
                    if (data.output == 'sucusses') {
                       replyQuestion(<?php  echo $this->userId;?>,quesId); 
                       replyQuestion(<?php  echo $this->userId;?>,quesId); 
                      
                    }
                }
            });
        }


    }

</script>