<?php if($this->zfcUserIdentity()){  ?>
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
$(function()
{ $("#close").click(function(){
        window.close();
    });
});
</script>
<style type="text/css">
body{ padding:0px;}
ul.resp-tabs-list, p{
font-size:13px;
}
.table-bordered td p{ margin-top:0;}
</style>
<link href="<?php echo $this->cdn(); ?>/css/website/bootstrap.css" type="text/css" rel="stylesheet" />
<link href="<?php echo $this->cdn(); ?>/css/website/global.css" type="text/css" rel="stylesheet" />
<link href="<?php echo $this->cdn(); ?>/css/website/profile.css" type="text/css" rel="stylesheet" />


<div class="inner-content" id="content">
        <div class="container">
            <div class="row">
                <div class="inner-block clearfix myprofile-content">

<div class="addChild_Container" style="margin-top:0px;">
            <h3 style="text-align:center">
              <div style="margin-bottom:10px;"><?php echo $paperName; ?></div>
			  <div style="margin-bottom:10px;">(<?php echo $paperClass.' - '.$paperSubject; ?>)</div>
			  <div style="margin-bottom:10px;">Marks: <?php echo $paperMarks; ?></div>
                          <?php if($paperTime != '00:00'){?> <div>Time: <?php echo $paperTime.' (hh:mm)'; ?></div><?php } ?>
            </h3>
            
            <div style="padding:20px;">
            <span>
			<div style="padding:10px 0px; font-size:14px;"><span style="color:#2C6085; font-weight:bold;">
            <img style="vertical-align:middle; height:13px;" src="<?php echo $this->cdn(); ?>/images/website/report/btn_next.png"/> Instruction</span> : <?php echo $paperInstruction; ?></div>

                 <?php
                if($paperSource == 'add')
                { 
                
                $x=1; 
                foreach($paperQuestion as $questions)
                {
                ?>
                 <div id="lms">
                        <table class="table table-bordered" >
                        
                        <tr>
                          <td align="left" width="10%"><strong style="font-size:16px;">Ques <?php echo $x; $x++; ?>.</strong></td>
                          <td align="left" width="80%" style="font-size:16px;"><?php echo html_entity_decode(stripslashes($questions['question']));?> <span style="float:right;">(Marks : <?php echo $questions['questionMarks']; ?>)</span></td> 
                        </tr>
                         </table>
                </div>
              <?php } } else if($paperSource == 'upload') { ?>
               <div id="lms">
                        <table class="mcqTable">
                        
                        <tr>
                          <td align="left" width="10%"><strong> Question: </strong></td>
                          <td align="left" width="80%">Question Files:</td> 
                        </tr>
                        <?php 
                        foreach($paperQuestion as $questions)
                        {
                            //echo '<pre>'; print_r($questions);
                            //$file_path = "http://10.1.9.99/uploads/mentorquestionfiles/".$questions->paperUploadFileName;
                            ?>
                        <?php if($questions->paperUploadFileType == 'ques')
                          { ?>
                        <tr>
                          <td align="left" width="10%"><strong> &nbsp; </strong></td>
                          <td align="left" width="80%">
                          
                          <a href="<?php echo $this->url('downloadquestion');?>/<?php echo $questions->paperUploadFileName; ?>">Download Question</a>
                          <span style="float:right;">(Marks : <?php echo $questions->paperUploadFileMarks; ?>)</span>
                          </td> 
                        </tr>
                        <?php } ?>
                    
                        <?php  } ?>
                        
                        
                        </table>
                </div>
              <?php } ?>
              
               
              
            </div>
            <div class="clear">&nbsp;</div>
             <div style="text-align:center;"><input type="button" class="btn btn-primary" id="close" name="close" value="Close"></div>
          </div>
       </form><?php }else{ ?>
	<script>
		window.location="<? echo $this->url('home');?>"
	</script>
<?php } ?>
 </div>
  </div>
   </div>
    </div>