<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Common\Module'                        => __DIR__ . '/Module.php',
    'Common\Controller\IndexController' => __DIR__ . '/src/Common/Controller/IndexController.php',
    'CommonTest\Framework\TestCase'        => __DIR__ . '/tests/Common/Framework/TestCase.php',
    'CommonTest\SampleTest'                => __DIR__ . '/tests/Common/SampleTest.php',
    'Common\Factory\Model\SlaveAdapter'     => __DIR__ .'src\Common\Factory\Model\SlaveAdapterServiceFactory.php',
);
