<link href="<?php echo $this->cdn("/css/website/profile.css"); ?>" rel="stylesheet">

<div id="content" class="profile-pages">
    <div class="container">
        <div class="row">
            <div class="myprofile-content">
                <div class="profile-view globle-click clearfix">
                    <strong>My Profile</strong>
                    <i class="icons-ar"></i>	
                </div>
                <?php echo $this->partial('zfc-user/user/profile-menu.phtml', array('page' => 'mychild', 'addedmentors' => $addedMentors, 'addedStudents' => $addedStudents)); ?>
                <section class="profile-block">
                    <div class="changePassword" >
                        <form class="form-horizontal" action="" name="login" id="login" method="post">
                            <input type="hidden" value="nav_1" id="nav_find">
                            <div style="height:25px;">
                                <span class="valid-error" id="confirmerrormsg" style="padding-left:205px;"></span>
                                <span class="valid-error greencolor" id="successmesg" style="padding-left:205px;"></span>
                            </div>
                            <?php if (isset($this->username) && $this->username != '') { ?>
                                <div class="form-group">
                                    <label for="cpass" class="col-sm-2 control-label">User Name</label>
                                    <div class="col-sm-5">
                                        <?php echo $this->username; ?>
                                    </div>
                                </div>
                                <?php
                            }
                            if (isset($_GET['token'])) {
                                ?>
                                <label for="cpass" class="col-sm-2 control-label">Old Password<sup>*</sup></label>
                                <div class="col-sm-5">
                                    <input type="password" class="form-control" id="oldpwd" value="" name="oldpwd" id="" placeholder="Enter your old password" onkeypress="changeSubmit(event)">
                                </div>
                                <span style="color:red;width:60%; margin-left:35%; float:left; margin-top:-20px; margin-bottom:10px;">(You got a password in your email)</span>
                            <?php }
                            ?>
                            <div class="form-group">
                                <label for="newpwd" class="col-sm-2 control-label">New Password<sup>*</sup></label>
                                <div class="col-sm-5">
                                    <input type="text" class="form-control" value="" name="newpwd" id="newpwd" onkeypress="changeSubmit(event)" placeholder="Enter New Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="confirm-pwd" class="col-sm-2 control-label">Confirm Password<sup>*</sup></label>
                                <div class="col-sm-5">
                                    <input class="form-control" type="text" value="" name="confirm-pwd" id="confirm-pwd" onkeypress="changeSubmit(event)" placeholder="Re-enter New password">
                                </div>
                            </div>
                            <div class="form-group last">
                                <label for="vpass" class="col-sm-2 control-label">&nbsp;</label>
                                <div class="col-sm-5">
                                    <button class="btn btn-primary" type="button" onClick="return changePassword();">RESET PASSWORD</button>
                                </div>
                            </div>
                            <?php
                            if (isset($_GET['id']) && $_GET['id'] != "") {
                                $id = $_GET['id'];
                            } else if (isset($_GET['userId']) && $_GET['userId'] != "") {
                                $id = $_GET['userId'];
                            }
                            ?>
                            <input type="hidden" id="userid" name="userid" value="<?php echo $id; ?>">
                        </form>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" language="JavaScript">
    document.forms['login'].elements['oldpwd'].focus();
    function changeSubmit(e) {
        if (e.keyCode == 13) {
            return changePassword();
        }
    }
    $('input,textarea').placeholder();
</script>
<script>
    function changePassword() {
        var flag = true;
<?php
$url = $this->URL('myChild');
if (isset($_GET['id']) && $_GET['id'] != "") {
    $url = $this->URL('home');
} else if (isset($_GET['userId']) && $_GET['userId'] != "") {
    $url = $this->URL('my-profile');
}
?>
        var userId = $("#userid").val();
        var oldpasswrd = $("#oldpwd").val();
        var passwrd = $("#newpwd").val();
        var cnfpwrd = $("#confirm-pwd").val();
        if (cnfpwrd == "") {
            $("#confirmerrormsg").css('display', 'block');
            $("#confirmerrormsg").html('All (*) fields are mandatory');
            flag = false;
            $("#newpwd").focus();
        }
        if (passwrd == "") {
            $("#confirmerrormsg").css('display', 'block');
            $("#confirmerrormsg").html('Please enter your new password!');
            flag = false;
            $("#newpwd").focus();
        }
        if (passwrd != "") {
            if (passwrd.length <= 5) {
                $("#confirmerrormsg").css('display', 'block');
                $("#confirmerrormsg").html('The password should be of minimum 6 characters.');
                flag = false;
                $("#newpwd").focus();
            }
        }
        if (oldpasswrd == passwrd) {
            $("#confirmerrormsg").css('display', 'block');
            $("#confirmerrormsg").html('New password should not be same as the old password.');
            flag = false;
            $("#newpwd").focus();
        }

        if (oldpasswrd != 'undefined') {
            if (oldpasswrd == "") {
                $("#confirmerrormsg").css('display', 'block');
                $("#confirmerrormsg").html('Please enter your old password!');
                flag = false;
                $("#oldpwd").focus();
            }
        }
        if (flag == false) {
            return false;
        } else {
<?php if (1) { ?>
                if (passwrd == cnfpwrd) {
                    $.ajax({
                        type: 'POST',
                        url: BASE_URL + '/user/changepasswordchild',
                        data: {cnfpwrd: cnfpwrd, userId: userId},
                        success: function(data) {
                            $("#confirmerrormsg").css('display', 'none');
                            $("#successmesg").css('display', 'block');
                            $("#successmesg").html('Child password has been changed.');
                            window.location = '<?php echo $url; ?>';
                        }
                    });
                } else {
                    $("#confirmerrormsg").css('display', 'block');
                    $("#confirmerrormsg").html('Child new password and confirm password do not match!');
                    $("#confirm-pwd").focus();
                }
<?php } else { ?>
                if (passwrd == cnfpwrd) {
                    $.ajax({
                        type: 'POST',
                        url: BASE_URL + '/user/check-password',
                        data: {oldpasswrd: oldpasswrd, userId: userId},
                        success: function(data) {
                            if (data.output == 'success') {

                                $.ajax({
                                    type: 'POST',
                                    url: BASE_URL + '/user/change-password',
                                    data: {cnfpwrd: cnfpwrd, userId: userId},
                                    success: function(data) {
                                        $("#confirmerrormsg").css('display', 'none');
                                        $("#successmesg").css('display', 'block');
                                        $("#successmesg").html('Password Changed Successfully');
                                        window.location = '<?php echo $url; ?>';
                                    }
                                });
                            } else {
                                $("#confirmerrormsg").css('display', 'block');
                                $("#confirmerrormsg").html('Please type your correct old password');
                            }
                        }
                    });

                } else {
                    $("#confirmerrormsg").css('display', 'block');
                    $("#confirmerrormsg").html('your new password and confirm password do not match!');
                    $("#confirm-pwd").focus();
                }
<?php } ?>

        }
    }
</script>