<link href="<?php echo $this->cdn("/css/website/profile.css"); ?>" rel="stylesheet">
<?php
if (isset($_GET['id'])) {
    $id = $_GET['id'];
} else {
    $id = '';
}
?>
<div id="content" class="profile-pages">
    <div class="container">
        <div class="row">
            <div class="myprofile-content">
                <div class="profile-view globle-click clearfix">
                    <strong>My Groups</strong>
                    <i class="icons-ar"></i>	
                </div>
                <?php
                echo $this->partial('user/index/profile-menu.phtml', array('page' => 'myGroups', 'addedmentors' => count($this->addedMentors), 'addedStudents' => count($this->addedStudents)));
                ?>
                <section class="profile-block">
                    <input type="hidden" value="nav_2" id="nav_find">
                    <div class="add-member clearfix">
                        <a href="javascript:void(0);"><i class="icons-plus img-circle"></i> Add Member</a>	
                    </div>
                    <div class="form-block">
                        <form class="form-horizontal" method="post" name="user-my-groups_form">
                            <div class="form-group">
                                <label for="emailadr" class="col-sm-2 control-label">Email ID<sup>*</sup></label>
                                <div class="col-sm-4">
                                    <input type="email" class="form-control" id="group_Email" placeholder="Please enter an email address" onkeypress="return groupSubmit(event);">
                                </div>
                                <button type="button" class="btn btn-primary" id="submitemail" onclick="return submitForm()">SUBMIT</button>
                            </div>

                            <div class="form-group">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="groupcheck" checked="checked"> <strong>Show other group members to the invitee</strong>
                                    </label>
                                </div>
                            </div>
                            <span class="errorfrm_mentor" id="erroremail"></span>								
                            <span class="errorfrm_mentor" id="succussesMessage"></span>
                        </form>
                        <p class="after-submit">After clicking "Submit" we will send an e-mail to the member for sign up and acceptance.</p>
                    </div>
                    <div class="tab-block" role="tabpanel">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" id="myGroupTab" role="tablist">
                            <li role="presentation" class="active activeClass"><a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab">My Group Members</a></li>
                            <li role="presentation" class="activeClass"><a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab">My Memberships</a></li>
                            <li role="presentation" class="activeClass"><a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab">My Messages</a></li>
                        </ul>
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="tab1">
                                <div class="groups-tbcontent common_table">
                                  <div class="table-responsive">
                                  	<div class="post_query clearfix"> 
                                    <div class="instruction-help clearfix"><a href="javascript:void(0)" class="icons-inshelp" data-toggle="tooltip" data-placement="top" title="List of members added to the group created by you."></a></div>
                                        
                                        <?php if (isset($this->activefriendcount) && ($this->activefriendcount != 0)) { ?>
                                         <a href="javascript:void(0);" class="post-query contactfordem" id="<?php echo $this->userObj->getId(); ?>">Post&nbsp;Query  <img src="<?php echo $this->cdn() ?>/images/click_arrow.png" style="vertical-align:middle"></a>
                                        <?php } ?>
                                        </div>
                                      
                                     <table class="table table-bordered">
                                    <?php if (isset($this->getstudentdetails) && count($this->getstudentdetails) != 0) { ?>
                                        <tr>
                                            <th >S.No.</th>
                                            <th>Name</th>
                                            <th>Board</th>
                                            <th>Class</th>
                                            <th>School</th>
                                            <th>Email</th>
                                            <th>Status</th>
                                            <th>Action</th>                                               



                                            <!--<?php if (isset($this->getstudentdetails) && count($this->getstudentdetails) != 0) { ?>
                                                                                                                                            <a href="javascript:void(0);" id="removegroup" class="remove-link" onclick="removeMembers()" style="line-height:inherit;">Delete</a>
                                            <?php } else { ?>
                                                                                                                                            <a href="javascript:void(0);"  style="display:none;" id="removegroup" class="remove-link" onclick="removeMembers()" style="line-height:inherit;">Delete</a>
                                            <?php } ?>-->




                                        </tr>
                                        <?php
                                    }
                                    $count = 1;
                                    if (isset($this->getstudentdetails) && count($this->getstudentdetails) != 0) {
                                        foreach ($this->getstudentdetails as $key => $groupdetails) {
                                            // if ($groupdetails->email_id != $_SESSION['user']['email']) {
                                            if ($groupdetails->first_name != '') {
                                                ?>	<tr id="<?php echo "mobile" . $key ?>" class="data-row  <?php if ($groupdetails->group_status != '1') { ?>faded<?php } ?>">
                                                                                                                                                                                                                    <!--<td id="data-row-<?php echo $key ?>-1" class="data-row-1"><input type="checkbox" name="checkgroupId" id="checkgroupId" value="<?php echo $groupdetails->group_id ?>"></td>-->
                                                    <td id="data-row-<?php echo $key ?>-2" class="data-row-2"><?php echo $count; ?></td>                                                                                       
                                                    <!--<td id="data-row-<?php echo $key ?>-3" class="data-row-3"><a href="<?php //echo $this->Url('user-profile');                    ?>?id=<?php echo $groupdetails->user_id; ?>"><?php
                                                    if (!empty($groupdetails->first_name)) {
                                                        echo $groupdetails->first_name;
                                                    } else {
                                                        ?>NA<?php } ?></td>-->
                                                    <td id="data-row-<?php echo $key ?>-3"><a  href="javascript:void(0);" data-toggle="modal" data-target="#userprofile-ac" data-whatever="@mdo" onclick="getPopupForms('userpopup',<?php echo $groupdetails->friend_id; ?>);"><?php
                                                            if (!empty($groupdetails->first_name)) {
                                                                echo $groupdetails->first_name;
                                                            } else {
                                                                ?>NA<?php } ?></td>
                                                    <td id="data-row-<?php echo $key ?>-4"><?php
                                                        if (!empty($groupdetails->board_name)) {
                                                            echo $groupdetails->board_name;
                                                        } else {
                                                            ?> NA <?php } ?></td>
                                                    <td id="data-row-<?php echo $key ?>-5"><?php
                                                        if (!empty($groupdetails->class_name)) {
                                                            echo $groupdetails->class_name;
                                                        } else {
                                                            ?> NA<?php } ?> </td>
                                                    <?php ?> <td id="data-row-<?php echo $key ?>-6"><?php
                                                    if (!empty($groupdetails->school_name)) {
                                                        echo $groupdetails->school_name;
                                                    } else {
                                                        ?>NA <?php } ?></td>
                                                    <td id="data-row-<?php echo $key ?>-7"><?php
                                                        if (!empty($groupdetails->email_id)) {
                                                            echo $groupdetails->email_id;
                                                        } else {
                                                            ?>NA <?php } ?></td>
                                                    <td id="data-row-<?php echo $key ?>-8"><?php if ($groupdetails->group_status == 0) { ?><span style='color:#ffbb04'>Pending</span><?php } elseif ($groupdetails->group_status == 3) { ?><span style='color:#cc3333'>Declined</span><?php } elseif ($groupdetails->group_status == 2) { ?><span style='color:#f00'>Deleted</span><?php } else { ?><span style='color:#169a00'>Accepted</span><?php } ?></td>
                                                    <?php if ($groupdetails->group_status != 2) { ?>
                                                        <td id="data-row-<?php echo $key ?>-8"><a title="Delete" href="javascript:void(0);"  class="remove-link" onclick="changegroupstatus('<?php echo $groupdetails->group_id ?>', '2', 'owner', '<?php echo $groupdetails->email_id ?>', 'Remove user', <?php echo $groupdetails->friend_id ?>)">Remove&nbsp;User</a></td>
                                                    <?php } ?>        

                                                    
                                                </tr>
                                                <?php
                                                $count++;
                                            }
                                            // }
                                        }
                                    } else {
                                        ?>
                                        <div class="instruction-help clearfix"><a href="javascript:void(0)" class="icons-inshelp" data-toggle="tooltip" data-placement="top" title="List of members added to the group created by you."></a></div>
                                        <div class="no-record"><p>No records found</p></div>
                                        <?php
                                        }
                                        ?>
                                        </table>
                                   </div>     
                                </div>
                                <div class="post_comment" id="groupowner_<?php echo $this->userObj->getId(); ?>">
                                	<button class="close" type="button" onclick="closepostquery('<?php echo $this->userObj->getId(); ?>')" id="close_button"><span aria-hidden="true">×</span></button>
                                       
                                        <form action="" name="post_comment" id="post_comment" method="post">
                                           <label class="message" id="msg_<?php echo $this->userObj->getId(); ?>">sssadd dssc s</label>                                              
                                            <textarea id="comment_text_<?php echo $this->userObj->getId(); ?>"  name="comment_text" placeholder="Post a query..." class="form-control"></textarea>
                                            <?php if ($this->userObj->getId() != "") { ?>
                                                <input type="button" class="btn btn-primary" name="qa_post" id="qa_post" onclick="commentgroupPost('<?php echo $this->userObj->getId() ?>')" value="POST">
                                            <?php } else { ?>
                                                <a class="showmnu fancybox" id="various1" onclick="getPopupForms('login');" href="javascript:void(0);" >
                                                    <input type="button" class="user-cmnt-form-submit" name="qa_post" id="qa_post" value=""></a>
                                            <?php } ?>
                                        </form>

                                        <div class="clear"></div>

                                    </div>
                                
                                
                            </div>
                            <div role="tabpanel" class="tab-pane" id="tab2">
                                <div id="view1" style="display:none;">
                                    <div>
                                        <label style="display:none;" class="message" id="msg_<?php echo $this->userObj->getId(); ?>"></label>
                                    </div>    
                                    
                                </div>
                                <div class="table-responsive">
                                <div class="groups-tbcontent common_table">

                                    <?php if (isset($this->getyourRequests) && count($this->getyourRequests) != 0) { ?>
                                        <table class="table table-bordered"> 
                                            <tbody>
                                                <tr>
                                                    <th>S.No.</th>
                                                    <th>Name</th>
                                                    <th>Board </th>
                                                    <th>Class</th>
                                                    <th>School</th>
                                                    <th>Email</th>
                                                    <th>View</th>
                                                    <th>Status</th>

                                                </tr>

                                                <?php if (isset($this->getyourRequests) && count($this->getyourRequests) != 0) { ?>
                                                    <?php
                                                }
                                                $count = 1;

                                                foreach ($this->getyourRequests as $key => $getrequests) {
                                                    if (count($this->requestIds) != 0) {
                                                        // if ($this->requestIds[$getrequests->user_id]['requestStatus'] == 0) {
                                                        if ($getrequests->first_name != '') {
                                                            ?>
                                                            <tr id="<?php echo "mobile" . $key ?>" class="data-row  <?php if ($getrequests->group_status != '1') { ?>faded<?php } ?>">
                                                                    <!--<td id="data-requests-<?php echo $key ?>-1" class="data-row-1"><input type="checkbox" name="checkgrouprequstId" id="checkgrouprequstId" value="<?php echo $getrequests->group_id ?>"></td>-->
                                                                <td id="data-requests-<?php echo $key ?>-2" class="data-row-2"><?php echo $count; ?></td>
                                                                <td id="data-requests-<?php echo $key ?>-3" class="data-row-3"><a  href="javascript:void(0);" data-toggle="modal" data-target="#userprofile-ac"  onclick="getPopupForms('userpopup',<?php echo $getrequests->user_id; ?>);"> <?php
                                                                        if (!empty($getrequests->first_name)) {
                                                                            echo $getrequests->first_name;
                                                                        } else {
                                                                            ?>NA<?php } ?> </a></td>
                                                                <td id="data-requests-<?php echo $key ?>-4" class="data-row-4"><?php
                                                                    if (!empty($getrequests->board_name)) {
                                                                        echo $getrequests->board_name;
                                                                    } else {
                                                                        ?>NA<?php } ?></td>
                                                                <td id="data-requests-<?php echo $key ?>-5" class="data-row-5"><?php
                                                                    if (!empty($getrequests->class_name)) {
                                                                        echo $getrequests->class_name;
                                                                    } else {
                                                                        ?>NA<?php } ?></td>
                                                                <td id="data-requests-<?php echo $key ?>-6" class="data-row-6"><?php
                                                                    if (!empty($getrequests->school_name)) {
                                                                        echo $getrequests->school_name;
                                                                    } else {
                                                                        ?>NA<?php } ?></td>
                                                                <td id="data-requests-<?php echo $key ?>-7" class="data-row-7"><?php
                                                                    if (!empty($getrequests->email_id)) {
                                                                        echo $getrequests->email_id;
                                                                    } else {
                                                                        ?>NA<?php } ?></td>
                                                            <?php } ?>
                                                            <td id="data-requests-<?php echo $key ?>-8" class="data-row-8"><?php if ($getrequests->group_status == 0) {
                                                                ?>Not Active<?php
                                                                } elseif ($getrequests->group_status == 2) {
                                                                    ?>Deleted<?php
                                                                } elseif ($getrequests->group_status == 3) {
                                                                    ?>Declined<?php
                                                                } else {
                                                                    ?>Activated<?php }
                                                                ?></td>


                                                            <?php if ($getrequests->group_status == 0) { ?>
                                                                <td id="data-row-<?php echo $key ?>-8" class="data-row-7 data-row-8">   <a title="Accept" href="javascript:void(0);"  class="remove-link" onclick="changegroupstatus('<?php echo $getrequests->group_id ?>', '1', '', '', 'Accept', <?php echo $getrequests->user_id ?>)">Accept</a>/
                                                                <!--<td id="data-row-<?php echo $key ?>-8" class="data-row-7 data-row-8">   <a title="Not Now" href="javascript:void(0);"  class="remove-link" onclick="changegroupstatus('<?php echo $getrequests->group_id ?>', '0','','','Not now')">Not&nbsp;now</a></td>-->
                                                                    <a title="Reject" href="javascript:void(0);"  class="remove-link" onclick="changegroupstatus('<?php echo $getrequests->group_id ?>', '3', '', '', 'Reject', <?php echo $getrequests->user_id; ?>)">Reject</a></td>
                                                            <?php } elseif ($getrequests->group_status == 1) { ?>

                                                                <td>
                                                                    <a href="javascript:void(0)" class="remove-link post-query" id="<?php echo $getrequests->user_id ?>" title="Post to Group">Post&nbsp;a&nbsp;query&nbsp;to&nbsp;group</a>&nbsp;/&nbsp;


                                                                    <a title="Delete" href="javascript:void(0);"  class="remove-link" onclick="changegroupstatus('<?php echo $getrequests->group_id ?>', '2', '', '', 'Leave group', <?php echo $getrequests->user_id ?>)">Delete</a>
                                                                <?php } elseif ($getrequests->group_status == 2) {
                                                                    ?>
                                                                <?php } elseif ($getrequests->group_status == 3) { ?>
                                                                <td id="data-row-<?php echo $key ?>-8" class="data-row-7 data-row-8">   <a title="Delete" href="javascript:void(0);"  class="remove-link" onclick="changegroupstatus('<?php echo $getrequests->group_id ?>', '2', '', '', 'Delete', <?php echo $getrequests->user_id ?>)">Delete</a></td>
                                                            <?php } else { ?>
                                                                <td id="#<?php echo "mobile" . $key ?>" class="view_details"><img onclick="showgetrequestsData('<?php echo $key ?>')" src="<?php echo $this->cdn() ?>/images/view_details.png" width="30px"/>Post&nbsp;Query/
                                                                    <a title="Delete" href="javascript:void(0);"  class="remove-link" onclick="changegroupstatus('<?php echo $getrequests->group_id ?>', '2', '', '', 'Leave group',<?php echo $getrequests->user_id ?>)">Delete</a></td>
                                                            <?php } ?>
                                                        </tr>
                                                        <tr>
                                                            <td colspan="15" style="padding:0 8px;"> 
                                                                <div>                                            
                                                                    <label style="display:none;" class="message" id="msg_<?php echo $getrequests->user_id; ?>"></label>
                                                                </div> 

                                                                <div class="post_comment clearfix" style="margin-top: 15px;" id="groupowner_<?php echo $getrequests->user_id ?>">
                <button class="close" type="button" onclick="closepostquery('<?php echo $this->userObj->getId(); ?>')" id="close_button"><span aria-hidden="true">×</span></button>
                                                                    <form action="" name="post_comment" id="post_comment" method="post">
                                                                <!--       <label class="message" id="msg_'<?php echo $getrequests->user_id ?>"></label>-->
                                                                        <textarea id="comment_text_<?php echo $getrequests->user_id ?>" name="comment_text" placeholder="Post a query..." class="form-control"></textarea>
                                                                        <input type="button" class="btn btn-primary" name="qa_post" id="qa_post" onclick="commentgroupPost('<?php echo $getrequests->user_id ?>')" value="POST">

                                                                    </form>
                                                                </div>    

                                                            </td>         
                                                        </tr>
                                                    <input type="hidden" id="checkStatus<?php echo $getrequests->group_id ?>" name="checkStatus<?php echo $getrequests->group_id ?>" value="<?php echo $getrequests->group_status ?>">
                                                    <?php
                                                    $count++;
                                                }
                                                }
                                                ?>
                                                </tbody>
                                            </table>
                                            <?php
                                        } else {
                                        ?>
                                        <div class="instruction-help clearfix"><a href="javascript:void(0)" class="icons-inshelp" data-toggle="tooltip" data-placement="top" title="List of members added to the group created by you."></a></div>
                                        <div class="no-record"><p>No records found</p></div>	
                                        <?php
                                    }
                                    ?>
                                  </div>     
                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="tab3">
                                <div class="groups-tbcontent">
                                    <form action="#" class="gb-form">
                                        <div class="clearfix">
                                            <div class="col-xs-12 col-sm-6 l-group">
                                                <div class="form-group clearfix">
                                                    <label class="col-sm-2">Name</label>
                                                    <div class="col-sm-10 padd-right">
                                                        <select class="CostomSelect" id="group_names" name="group_names" onchange="allQuestions()">
                                                            <option value="">---Select---</option>
                                                            <?php
                                                            if (isset($this->userNames) && $this->userNames != "") {
                                                                foreach ($this->userNames as $userNames) {
                                                                    
                                                                    ?>
                                                                    <?php if ($userNames->firstName != "") { ?>
                                                                        <option value="<?php echo $userNames->user_id; ?>"><?php echo $userNames->firstName; ?></option>
                                                                    <?php } ?>
                                                                    <?php
                                                                }
                                                            }
                                                            ?> 
                                                        </select>
                                                    </div>	
                                                </div>
                                                <div class="form-group clearfix">
                                                    <label class="col-sm-2">Subject</label>
                                                    <div class="col-sm-10 padd-right">
                                                        <select class="CostomSelect" id="subjects" name="subjects">
                                                            <option value="">---Select---</option>
                                                        </select><span style="display:none;" id="loadSubjectActivity"><img src="<?php echo $this->cdn() ?>/images/website/loader16.gif"></span>
                                                    </div>	
                                                </div>
                                            </div>
                                            <div class="col-xs-12 col-sm-6 r-group">
                                                <div class="clearfix">	
                                                    <div class="col-sm-6 padd-left">
                                                        <div class="form-group clearfix">
                                                            <label class="col-sm-3 col-md-2">Board</label>
                                                            <div class="col-sm-9 col-md-10 two-cols">
                                                                <select class="CostomSelect" id="boards" name="boards">
                                                                    <option value="">---Select---</option>
                                                                    <?php if (count($this->getQuestions)) { 
                                                                        
                                                                        
                                                                        ?>
                                                                        <?php
                                                                        
                                                                        if (isset($this->boards)) {
                                                                            foreach ($this->boards as $key=>$boards) {
                                                                              ?>													
                                                                                <option value="<?php echo $key; ?>"><?php echo $boards; ?></option>
                                                                                <?php
                                                                            }
                                                                        }
                                                                        ?> 
                                                                    <?php } ?>
                                                                </select>
                                                            </div>	
                                                        </div>	
                                                    </div>
                                                    <div class="col-sm-6 padd-right">
                                                        <div class="form-group clearfix">
                                                            <label class="col-sm-3 col-md-2">Class</label>
                                                            <div class="col-sm-10 col-md-10 two-cols">
                                                                <select class="CostomSelect" id="classnames" name="classnames">
                                                                    <option value="">---Select---</option>
                                                                </select><span style="display:none;" id="loadClassActivity"><img src="<?php echo $this->cdn() ?>/images/website/loader16.gif"></span>
                                                            </div>	
                                                        </div>	
                                                    </div>
                                                </div>
<!--                                                <div class="form-group custom-group clearfix">
                                                    <label class="col-sm-2">Group</label>
                                                    <div class="col-sm-10 r-width">
                                                        <select class="CostomSelect" id="group" name="subjects" onchange="allQuestions()">
                                                            <option value="">---Select---</option>
                                                        </select>
                                                    </div>	
                                                </div>-->
                                                <div class="form-group clearfix">
                                                <label class="col-sm-2">Chapter</label>
                                                <div class="col-sm-10 r-width">
                                                    <select class="CostomSelect" id="chapter" name="chapter">
                                                        <option value="">---Select---</option>
                                                    </select><span style="display:none;" id="loadChapterActivity"><img src="<?php echo $this->cdn() ?>/images/website/loader16.gif"></span>
                                                </div>	
                                            </div>
                                            </div>	
                                        </div>
                                        <!--<div class="col-xs-12 float-none padd">-->
                                            
                                        <!--</div>-->
                                        <div id="all_page_question" class="clearfix"> 
                                            <?php echo $this->partial('assessment/index/pagination-questions.phtml', array('currentPage' => $this->currentPage, 'resultsPerPage' => $this->resultsPerPage, 'getQuestions' => $this->getQuestions, 'countposts' => $this->countposts, 'currentchapter_details' => $this->currentchapter_details, "userId" => $this->userId)); ?>
                                        </div>
                                    </form>
                                    <!-- <p class="not-found">No records found, answers or comments.</p> -->
                                </div>
                            </div>

                        </div>
                    </div> <!-- TAB BLOCK -->
                </section>
                <div class="datarequest_popup">&nbsp;</div>
            </div> 
        </div>	 
    </div>
</div>
<div class="modal fade addchild-popup userprofile-popup" id="userprofile-ac" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="clearfix"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
       <div class="modal-body_cls" id="model_body">
        random numbering
      </div>
    </div>
  </div>
</div>
<script>
<?php if (isset($_GET['id'])) { ?>
        $(document).ready(function() {
            closeMember();
        });
<?php } ?></script>
<script type="text/javascript">
    setTimeout(function() {
        document.getElementById('group_Email').focus();
    }, 500);</script>
<script type="text/javascript">
    var a = $("#nav_find").val();
    $("#" + a).addClass("container-nav-current");
    $(function() {
       // $('input, textarea').placeholder();
    });</script>
<script type="text/javascript">
    function commentgroupPost(groupowner_id) {
        $('#loadingPost').show();
        var groupownerId = groupowner_id;
        var commenttext = $("#comment_text_" + groupowner_id).val();		
        if (commenttext == "") {
            alert("Please enter your comment.");
            $("#comment_text").focus();
            return false;
        }
        $.ajax({
            async: false,
            type: 'POST',
            url: '<?php echo $this->Url('comments'); ?>',
            dataType: "json",
            data: {groupownerId: groupownerId, commenttext: commenttext},
            success: function(data) {
                if (data.output == 'success') {                    
                    $("#comment_text_" + groupowner_id).val('');
                    $("#msg_" + groupowner_id).show();
                    $("#msg_" + groupowner_id).html('Query Posted Successfully');
                    
                    setTimeout(function() { $("#msg_" + groupowner_id).hide();
                     $('#loadingPost').hide();
                    $(".post_comment").hide();
                   	
                    $(".message").show();
                    $("#comments").html(data);  
                    }, 2000);
                   // $("#msg_" + groupowner_id).show().delay(1000).fadeOut();
                   
                }

            }
        });
    }
    function groupSubmit(e) {
        if (e.keyCode == 13) {
            submitForm();
            return false;
        }
    }
    
//    $('#submitemail').on('click', function (e) {
//       submitForm(); 
//     //your awesome code here
//
//})
    
    function submitForm() {
        
        $('#erroremail').html('');
        $('#succussesMessage').html('');
        var emailCheck = $('#group_Email').val();
       
        //var groupstatus = $('#showgroups').val();
        if ($('#showgroups').is(':checked')) {
            var chk = 1;
        } else {
            var chk = 0;
        }

        var flag = true;

        var loggedemailid = '<?php echo $this->userObj->getEmail(); ?>';
        if (emailCheck == loggedemailid) {
            alert('You are already logged in');
            flag = false;
        }
        
        if (emailCheck == "") {
            $('#succussesMessage').html('');
            $('#erroremail').html('Please enter an email address. ');
            $('#erroremail').show().delay(2000).fadeOut();
            flag = false;
        } else if (checkEmail(emailCheck) == false) {
            $('#succussesMessage').html('');
            $('#erroremail').html('Please enter a valid email address.');
            $('#erroremail').show().delay(2000).fadeOut();
            flag = false;
        }
           
        if(flag == false) {
            return false;
        }else {
            $('#loadding2').hide();
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->Url('checkEmail'); ?>',
                dataType: "json",
                data: {email: emailCheck, flag: 'verify'},
                success: function(data) { 
                    
                    if (data.output != 'notSuccess') { 
                        $('#succussesMessage').html('');
                        $('#erroremail').html('This request was sent earlier. Please check your group entries. ');
                        $('#erroremail').show().delay(2000).fadeOut();
                        $('#group_Email').val('');
                    } else {  
                        $.ajax({
                            type: 'POST',
                            url: '<?php echo $this->Url('checkEmail'); ?>',
                            dataType: "json",
                            data: {email: emailCheck, flag: true},
                            success: function(data) { 

                                if (data.output != 'notSuccess') { 
                                    $('#succussesMessage').html('');
                                    $('#erroremail').html('Request to this mailid is already sent');
                                    $('#erroremail').show().delay(2000).fadeOut();
                                    $('#group_Email').val('');
                                } else { 
                                    $('#loadding2').show();
                                    $.ajax({
                                        type: 'POST',
                                        url: '<?php echo $this->Url('addgroupdetails'); ?>',
                                        data: {emailid: emailCheck, flag: true, groupstatus: chk},
                                        success: function(data) { 
                                            $('#loadding2').hide();
                                            if (data.output == 'error')
                                            {
                                                $('#erroremail').html('');
                                                $('#succussesMessage').html(data.message);
                                                $('#succussesMessage').show().delay(2000).fadeOut();
                                                $('#group_Email').val('');
                                            }
                                            else if (data.output == 'exist') {
                                                $('#removegroup').show();
                                                $('#erroremail').html('');
                                                $('#succussesMessage').html('Request to this mailid is already sent');
                                                $('#succussesMessage').show().delay(2000).fadeOut();
                                                $('#group_Email').val('');
                                            }
                                            else {
                                                if (data) {
                                                    $('#removegroup').show();
                                                    $('#erroremail').html('');
                                                    $('#succussesMessage').html('Your request has been sent successfully');
                                                    $('#succussesMessage').show().delay(2000).fadeOut();
                                                    $('#group_Email').val('');
                                                    location.reload();
                                                    //$('#groupTable').html(data);

                                                } else {
                                                    $('#erroremail').html('');
                                                    $('#succussesMessage').html('Your request has been not sent. Please try again');
                                                    $('#succussesMessage').show().delay(2000).fadeOut();
                                                    $('#group_Email').val('');
                                                }
                                            }
                                        }
                                    });
                                }
                            }
                        });
                    }
                }
            });
        }
    }
    function removeMembers() {
        var selectBoxes = "";
        var checkboxes = document.getElementsByTagName("INPUT");
        var len = checkboxes.length;
        var cnt = 0;
        for (var i = 0; i < len; i++)
        {
            if (checkboxes[i].name == "checkgroupId")
            {
                if (checkboxes[i].checked)
                {
                    selectBoxes += '"' + checkboxes[i].value + '"' + ',';
                    cnt++;
                }
            }
        }
        if (cnt == 0)
        {
            alert('Please select the row(s) to delete')
        } else {

            $.ajax({
                type: 'POST',
                url: BASE_URL + '/account/delete-group',
                data: {ids: selectBoxes, report_type: 'members'},
                success: function(data) {

                    if (data == 'notFound	') {
                        $('#succussesMessage').html('');
                        $('#removegroup').hide();
                        $('#groupTable').html('<tr class="data-row"><td>No records found</td></tr><tr class="space-row"></tr>');
                    } else {
                        $('#erroremail1').html('');
                        $('#succussesMessage').html('');
                        $('#succussesMessage2').html('Selected row(s) successfully Deleted.');
                        $('#groupTable').html(data);
                    }
                }
            });
        }
    }
    function removeFriendrequest() {
        var selectBoxes = "";
        var checkboxes = document.getElementsByTagName("INPUT");
        var len = checkboxes.length;
        var cnt = 0;
        for (var i = 0; i < len; i++)
        {
            if (checkboxes[i].name == "checkgrouprequstId")
            {
                if (checkboxes[i].checked)
                {
                    selectBoxes += '"' + checkboxes[i].value + '"' + ',';
                    cnt++;
                }
            }
        }
        if (cnt == 0)
        {
            alert('Please select the row(s) to delete')
        } else {
            $.ajax({
                type: 'POST',
                url: BASE_URL + '/account/delete-group',
                data: {ids: selectBoxes, report_type: 'requestMembers'},
                success: function(data) {
                    if (data != 'notFound') {
                        $('#requestRemove').show('');
                        $('#hidgroupcheckemail').val('1');
                        $('#succussesMessage').html('');
                        $('#succussesMessage2').html('Selected row(s) successfully Deleted.');
                        $('#groupRequest').html(data);
                    } else {
                        $('#succussesMessage').html('');
                        $('#requestRemove').hide('');
                        $('#groupRequest').html('<tr class="data-row"><td>No records found</td></tr><tr class="space-row"></tr>');
                    }
                }
            });
        }
    }
</script>
<script>
    function studentOperations(type) {
        var selectBoxes = "";
        var checkboxes = document.getElementsByTagName("INPUT");
        var len = checkboxes.length;
        var cnt = 0;
        for (var i = 0; i < len; i++)
        {
            if (checkboxes[i].name == "checkgrouprequstId")
            {
                if (checkboxes[i].checked)
                {
                    selectBoxes += checkboxes[i].value + ',';
                    cnt++;
                }
            }
        }
        if (cnt == 0)
        {
            if (type == 'active') {
                alert('Please select the rows to Activate')
            } else if (type == 'deActive') {
                alert('Please select the rows to DeActivate')
            }

        } else {
            var groupIds = selectBoxes.split(',');
            if (type == 'active') {
                for (i = 0; i < groupIds.length; i++) {
                    var value = $('#checkStatus' + groupIds[i]).val();
                    if (value == 1) {
                        alert('Please select only NotActivate persons');
                        return false;
                    } else {
                        $('#loadding3').show();
                    }
                }
            } else if (type == 'deActive') {
                for (i = 0; i < groupIds.length; i++) {
                    var value = $('#checkStatus' + groupIds[i]).val();
                    if (value == 0) {
                        alert('Please select only Activated persons');
                        return false;
                    } else {
                        $('#loadding4').show();
                    }
                }
            }
            $.ajax({
                type: 'POST',
                url: BASE_URL + '/account/group-operations',
                data: {ids: selectBoxes, type: type},
                success: function(data) {
                    if (type == 'delete') {
                        $('#loadding2').hide();
                    } else if (type == 'active') {
                        $('#loadding3').hide();
                    } else if (type == 'deActive') {
                        $('#loadding4').hide();
                    }
                    if (data) {
                        if (type == 'active') {
                            $('#hidgroupcheckemail').val('1');
                            $('#succussesMessage3').html('Selected member are acivated');
                            $('#succussesMessage4').html('');
                            $('#succussesMessage2').html('');
                            var groupIds = selectBoxes.split(',');
                            for (i = 0; i < groupIds.length; i++) {
                                var value = $('#checkStatus' + groupIds[i]).val();
                                if (value == 0) {
                                    var countN = $('#totalNotifications').html();
                                    var newN = parseInt(countN) - 1;
                                    if (newN != 0) {
                                        $('#totalNotifications').html(newN);
                                        $('#groups' + groupIds[i]).hide();
                                    } else {
                                        $('#notifiBox').hide();
                                    }
                                }
                            }
                        } else if (type == 'deActive') {
                            $('#hidgroupcheckemail').val('1');
                            $('#succussesMessage3').html('');
                            $('#succussesMessage4').html('Selected member are deAcivated');
                            $('#succussesMessage2').html('');
                        }
                        $('#ajaxOperationsGroups').html(data);
                    } else {
                        $('#succussesMessage2').html('Results not found!');
                    }
                }
            });
        }
    }
    function closeMember() {
        $("#addMember").hide();
        $("#show_activity").show();
    }
    function postHide() {
        $("#texthide").show();
    }
    $( document ).ready(function() {
    $("#boards").change(function() {
        $("#classnames").val("");
        $("#classnames").next().html("---Select---");
        $("#subjects").val("");
        $("#subjects").next().html("---Select---");
        $("#chapter").val("");
        $("#chapter").next().html("---Select---");
        var group_name = $("#group_names").val();
        var board = $("#boards").val();
        $.ajax({
            type: 'POST',
            url: BASE_URL + '/lms/index/custom-containerlist/'+$(this).val(),
            data: {board_id: board},
            success: function(data) {
                    $("#classnames option[value!='']").each(function() {
                            $(this).remove();
                    });
                    //var data=jQuery.parseJSON(data);                     
                    var select = document.getElementById('classnames');
                    $.each(data.options, function(key,obj)
                    {
                        var opt = document.createElement('option');
                        opt.value = data.options[key].rack_id;
                        opt.innerHTML = data.options[key].rack_name;
                        select.appendChild(opt);

                    });
            }
        });
        allQuestions();
    });
    $("#classnames").change(function() {
        if ($("#boards").val() == "") {
            alert('Please select a board');
            return false;
        } else {
            $("#subjects").val("");
            $("#subjects").next().html("---Select---");
            $("#chapter").val("");
            $("#chapter").next().html("---Select---");
            var classid = $("#classnames").val();
            $.ajax({
                type: 'POST',
                url: BASE_URL + '/getSubjectListByClass',
                data: {classid: classid},
                success: function(data) {
                    $("#subjects option[value!='']").each(function() {
                            $(this).remove();
                    });
                    var data=jQuery.parseJSON(data);   
                    if (data.output) {
                        var select = document.getElementById('subjects');
                        $.each(data.subjectlist, function(key,obj)
                        {                            
                        var opt = document.createElement('option');
                        opt.value = key;
                        opt.innerHTML = data.subjectlist[key];
                        select.appendChild(opt);

                        });
                    }
                }
            });
            allQuestions();
        }
    });
    $("#subjects").change(function() {
        
        var subjectid = $("#subjects").val();
        var classid = $("#classnames").val();
        if ($("#boards").val() == "") {
            alert('Please select a board');
            return false;
        } else if (classid == "") {
            alert('Please select a class');
            return false;
        } else {
            $("#chapter").val("");
            $("#chapter").next().html("---Select---");
            $.ajax({
                type: 'POST',
                url: BASE_URL + '/getChaptersList',
                data: {class_id: classid, subject_id: subjectid},
                success: function(data) {
                    $("#chapter option[value!='']").each(function() {
                            $(this).remove();
                    });
                    var data=jQuery.parseJSON(data);
                    if (data.output == 'success') {
                        var select = document.getElementById('chapter');
                        $.each(data.chapterList, function(key,obj)
                        {                            
                        var opt = document.createElement('option');
                        opt.value = key;
                        opt.innerHTML = data.chapterList[key];
                        select.appendChild(opt);

                        });
                    }
                }
            });
            allQuestions();
        }
    });
    $("#chapter").change(function() {
        var board = $("#boards").val();
        var classid = $("#classnames").val();
        var subjectid = $("#subjects").val();
        if ($("#boards").val() == "") {
            alert('Please select a board');
            return false;
        } else if (classid == "") {
            alert('Please select a class');
            return false;
        } else if (subjectid == "") {
            alert("Please select a subject");
            return false;
        }
        allQuestions();
    });
 });
    function replyQuestion(userid, questionid) {
        $("#postReply" + questionid).hide();
        $("#replyAnswers" + questionid).toggle();
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->Url('reply-answers'); ?>',
            data: {userid: userid, questionid: questionid},
            success: function(data) {
                if (data) {
                    $("#replyAnswers" + questionid).html(data);
                }
            }
        });
    }
    function replyAnswer1(questionid) {
        $("#postReply" + questionid).toggle();
        $("#replyAnswers" + questionid).hide();
    }
    function postQuestion(questionid, userid, replyCount) {
        var postReply = $("#replyAnswer" + questionid).val();
        if (postReply == "") {
            alert("Please enter your message");
            $("#replyAnswer" + questionid).focus();
            return false;
        }
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->Url('reply-add'); ?>',
            dataType: "json",
            data: {userid: userid, questionid: questionid, replymessage: postReply},
            success: function(data) {
                if (data.output == 'success') {
                    $("#postReply" + questionid).toggle();
                    $("#view" + questionid).show();
                    $("#countReplys" + questionid).html(data.count_reply);
                    $("#replyAnswer" + questionid).val('');
                }
            }
        });
    }
    function changegroupstatus(Id, Status, actortype, useremail, type, friendId)
    {
        var groupId = Id;
        var groupStatus = Status;
        var actortype = actortype;
        var useremail = useremail;
        var type = type;
        var friendId = friendId;
        if (type == 'Accept') {
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->Url('changegroupstatus'); ?>',
                data: {groupId: groupId, groupStatus: groupStatus, actortype: actortype, useremail: useremail, type: type, friendId: friendId},
                dataType: "json",
                success: function(data) {
                    $('#loaddingActivity').hide();
                    if (data['output'] == 'sucusses') {
                        location.reload();
                    }
                }
            });
        } else {

            if (confirm('Are you sure you want to ' + type + '?')) {

                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->Url('changegroupstatus'); ?>',
                    dataType: "json",
                    data: {groupId: groupId, groupStatus: groupStatus, actortype: actortype, useremail: useremail, type: type, friendId: friendId},
                    success: function(data) {
                        $('#loaddingActivity').hide();
                        if (data['output'] == 'sucusses') {
                            location.reload();
                        }
                    }
                });
            }
        }


    }
    function allQuestions() {
        
        var group_name = $("#group_names").val();
        var board = $("#boards").val();
        var classid = $("#classnames").val();
        var subjectid = $("#subjects").val();
        var chapterid = $("#chapter").val();
        
        var type = 'group';
        $('#loaddingActivity').show();
        $.ajax({
            type: 'POST',
            url: BASE_URL + '/all-questions',
            data: {group_name: group_name, board: board, classid: classid, subjectid: subjectid, chapterid: chapterid, type: type},
            success: function(data) {
                $('#loaddingActivity').hide();
                if (data) {
                    $("#all_page_question").html(data);
                }
            }
        });
    }
    function postsPrevious(type, currentPage, resultsPerPage) {
        $('#loadingprev').show();
        var group_name = $("#group_names").val();
        var board = $("#boards").val();
        var classid = $("#classnames").val();
        var subjectid = $("#subjects").val();
        var chapterid = $("#chapter").val();
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->Url('pagination-questions'); ?>',
            data: {currentPage: currentPage, resultsPerPage: resultsPerPage, group_name: group_name, board: board, classid: classid, subjectid: subjectid, chapterid: chapterid, type: type},
            success: function(data) {
                $('#loadingprev').hide();
                if (data) {
                    $("#all_question").html(data);
                }
            }
        });
    }
    function postsNext(type, currentPage, resultsPerPage) {
        $('#loadingnext').show();
        var group_name = $("#group_names").val();
        var board = $("#boards").val();
        var classid = $("#classnames").val();
        var subjectid = $("#subjects").val();
        var chapterid = $("#chapter").val();
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->Url('pagination-questions'); ?>',
            data: {currentPage: currentPage, resultsPerPage: resultsPerPage, type: type, group_name: group_name, board: board, classid: classid, subjectid: subjectid, chapterid: chapterid},
            success: function(data) {
                $('#loadingnext').hide();
                if (data) {
                    $("#nextPost").hide();
                    $("#all_question").html(data);
                }
            }
        });
    }


    function closepostquery(id) {
        $("#groupowner_" + id).css('display', 'none');
    }

    $(function() {
        $(".groupact_dd").each(function() {
            $(this).before("<span class='groupact_dd_span'>---Select---</span>")
        });
        $('.groupact_dd').change(function() {
            $(this).prev().html($('option:Selected', $(this)).text());
            $(this).prev().width($(this).width() - 35);
        });
        $('.groupact_fres').click(function() {
            $('#groupact_form')[0].reset();
            $('.groupact_dd').change();
        })
    });</script>
<?php if (count($this->getQuestions) > 0) { ?>
    <?php foreach ($this->getQuestions as $allQuestions) { ?>
        <div class="groupact_popcont<?php echo $allQuestions->user_id; ?>" style="display: none;">
            <div class="cmnt-table">
                <div class="cmnt-row">
                    <div class="cmnt-cell cmnt-cellpopimg">
                        <?php if ($allQuestions->user_photo != '') { ?>
                            <img src="<?php echo $this->basePath() ?>/uploads/profileimages/<?php echo $allQuestions->user_photo; ?>" width="90" />
                        <?php } ?>
                        <div><?php echo $allQuestions->name; ?></div>
                    </div>
                    <div class="cmnt-cell">
                        <div class="groupact_half">
                            <div>Board:&nbsp;&nbsp;&nbsp;&nbsp; <?php
                                if ($allQuestions->board_name != '') {
                                    echo $allQuestions->board_name;
                                } else {
                                    echo "NA";
                                }
                                ?></div>
                            <div>Class:&nbsp;&nbsp;&nbsp;&nbsp;<?php
                                if ($allQuestions->class_name != '') {
                                    echo $allQuestions->class_name;
                                    ;
                                } else {
                                    echo "NA";
                                }
                                ?></div>
                            <div>School:&nbsp;&nbsp;&nbsp;&nbsp;<?php
                                if ($allQuestions->school_name != '') {
                                    echo $allQuestions->school_name;
                                    ;
                                } else {
                                    echo "NA";
                                }
                                ?></div> 
                        </div>
                        <div class="groupact_half">
                            <div>Email:&nbsp;&nbsp;&nbsp;&nbsp;<?php
                                if ($allQuestions->email_id != '') {
                                    echo $allQuestions->email_id;
                                } else {
                                    echo "NA";
                                }
                                ?></div> 
                            <div>Phone:&nbsp;&nbsp;&nbsp;&nbsp;<?php
                                if ($allQuestions->mobile != '') {
                                    echo $allQuestions->mobile;
                                } else {
                                    echo "NA";
                                }
                                ?></div> 
                            <div>Location:&nbsp;&nbsp;&nbsp;&nbsp;<?php
                                if ($allQuestions->address != '') {
                                    echo $allQuestions->address;
                                } else {
                                    echo "NA";
                                }
                                ?></div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
    }
}
?>
<!--<div class="overlay_logins" id="overlay_logins"></div>
<div style="position:absolute; top:50%; z-index: 9999; left:20%">
    <div id="groupact_pop" style="display: none;">
        <a class="sroupact_close" href="javascript:void(0);" onclick="closepopup()" title="Delete"></a>
        <h2>Profile</h2>
        <div class="groupact_popcont" >
        </div>
    </div>
</div>-->

<script>
$(function() {
	$('[data-toggle="tooltip"]').tooltip();
	
})
    function getUserdata(id) {

        var htmlData = $('.groupact_popcont' + id).html();

        //$("#overlay_logins").css({display: "block"});
        $('#model_body_p').html(htmlData);


    }

    function closepopup() {
        $('#groupact_pop').hide();
        $("#overlay_logins").css({display: "none"});

    }
</script>
<script>
    var tabId = <?php echo $this->tabId;?>;
   
    $(document).ready(function() {  
         $('.activeClass').removeClass('active');
         $("#tab1").removeClass('active');
          $("#myGroupTab li").eq(tabId-1).addClass('active');
          $("#tab"+tabId).addClass('active');
        $(".main-bg").height($(".right-content").height() + 7);
    });
    $(window).resize(function() {
        $(".main-bg").height($(".right-content").height() + 7);
    });
    function getPopupForms(type, id) {
        var urlPath = '';
        if (type == 'userpopup') {
            var userId = id;
            var baseURL = '<?php echo $this->url('userprofile'); ?>';
            urlPath = baseURL + '?id=' + userId;
        }
        $.ajax({
            type: 'POST',
            url: urlPath,
            success: function(data) {
                if(type == 'userpopup') {
                    $('.modal-body_cls').html(data);
                    $('#userprofile-ac').modal('show');
                }
            }
        });
    }

</script>
<script>
    function closedata()
    {
        $(".datashow_popup").hide();
        $(".backbase_transform").hide();
        $("#close_button").hide();
    }
    function showPopupData(key)
    {
        var firstname = $("#data-row-" + key + "-3").html();
        var board_name = $("#data-row-" + key + "-4").html();
        var class_name = $("#data-row-" + key + "-5").html();
        var school_name = $("#data-row-" + key + "-6").html();
        var email_id = $("#data-row-" + key + "-7").html();
        var group_status = $("#data-row-" + key + "-8").html();
        var data = "<a id='close_button' onclick='closedata()' href='JavaScript:void(0)'></a><div class='datapopup_class'>" + firstname + "</div><div class='datapopup_class'>" + board_name + "</div><div class='datapopup_class'>" + class_name + "</div><div class='datapopup_class'>" + school_name + "</div><div class='datapopup_class'>" + email_id + "</div><div class='datapopup_class'>" + group_status + "</div>";
        $(".datashow_popup").html(data).show();
        $(".backbase_transform").show();
        $("#close_button").show();
    }
</script>
<script>
    function closerequest()
    {
        $(".datarequest_popup").hide();
        $(".backbase_transform").hide();
        $("#close_button").hide();
    }
    function showgetrequestsData(key)
    {
        var first_name = $("#data-requests-" + key + "-3").html();
        var board_name = $("#data-requests-" + key + "-4").html();
        var class_name = $("#data-requests-" + key + "-5").html();
        var school_name = $("#data-requests-" + key + "-6").html();
        var email_id = $("#data-requests-" + key + "-7").html();
        var group_status = $("#data-requests-" + key + "-8").html();
        var data = "<a id='close_button' onclick='closerequest()' href='JavaScript:void(0)'></a><div class='datapopup_class'>" + first_name + "</div><div class='datapopup_class'>" + board_name + "</div><div class='datapopup_class'>" + class_name + "</div><div class='datapopup_class'>" + school_name + "</div><div class='datapopup_class'>" + email_id + "</div><div class='datapopup_class'>" + group_status + "</div>";
        $(".datarequest_popup").html(data).show();
        $(".backbase_transform").show();
        $("#close_button").show();
    }
  $(".post-query").click(function() {
      
            var id = $(this).attr("id");
            $(".post_comment").hide();
            console.log($("#groupowner_" + id).show());
            $("#groupowner_" + id).show();
            $(".message").hide();
        });
        $('#add-member-tog').click(function() {
            $('#user-my-groups_form').toggle();
            $(window).resize();
        });
        if($('a.tTip').length>0)
        $('a.tTip').tinyTips('light', 'title');
    
    function refreshCaptcha()
    {
        var img = document.images['captchaimg'];
        img.src = img.src.substring(0, img.src.lastIndexOf("?")) + "?rand=" + Math.random() * 1000;
        $('[placeholder]').blur();
    }  
    
    
</script>
