<link rel="stylesheet" href="<?php echo $this->basePath("css/website/profile.css"); ?>" type="text/css" media="screen" />
<?php if ($this->zfcUserIdentity()) { ?>
    <div id="content" class="profile-pages">
        <div class="container">
            <div class="row">
                <div class="myprofile-content">
                    <div class="profile-view globle-click clearfix">
                        <strong>My Child</strong>
                        <i class="icons-ar"></i>	
                    </div>
                <?php echo $this->partial('user/index/profile-menu.phtml', array('page' => 'mychild', 'addedmentors' => count($this->addedMentors), 'addedStudents' => count($this->addedStudents))); ?>
                <section class="profile-block">
                    <input type="hidden" value="nav_5" id="nav_find">
                    <div class="add-member clearfix">
                        <a href="javascript:void(0)"  data-toggle="modal" data-target="#addchild" data-whatever="@mdo"><i class="icons-plus img-circle"></i> Add Child</a>
                    </div>
                    <span id="deletemsg" style="color:green"></span>
                    <div class="addChild_Container">
                        <h3>My Child</h3>
                        <div class="mentor-inner common_table">
                        	<div class="table-responsive">
                            <?php if (count($this->childData) != 0 || count($this->parentrequestsent) != '0' || count($this->childrequestreceive) != '0') { ?>
                                <table class="table table-bordered">
                                    <tr>
                                        <th>Name</th>
                                        <th>Username</th>
                                        <th>Board</th>
                                        <th>Class</th>
                                        <th>View Progress</th>
                                        <th>Action / Status</th>
<!--                                        <th>Delete</th>-->
                                    </tr>
                                    <?php
                                    foreach ($this->parentrequestsent as $key => $parentrequest) {
                                        ?>
                                        <tr>
                                            <td><?php echo $parentrequest->first_name; ?></td>
                                            <td><a data-toggle="modal" data-target="#userprofile" data-whatever="@mdo" class="showmnu" id="" onclick="getPopupForms('userpopup', '<?php echo $parentrequest->userid; ?>');" href="#" ><?php echo $parentrequest->email_id; ?></a></td>
                                            <td><?php
                                                if ($parentrequest->board_name != '') {
                                                    echo $parentrequest->board_name;
                                                } else {
                                                    ?> NA<?php } ?></td>
                                            <td><?php
                                                if ($parentrequest->class_name != '') {
                                                    echo $parentrequest->class_name;
                                                } else {
                                                    ?> NA<?php } ?></td>
                                            <!--<td  width="15%" align="center"><img width="15" height="15" border="0" src="<?php echo $this->cdn() ?>/images/add.gif"></td>-->
                                            <td><img width="17" height="17" style="opacity: 0.5" border="0" src="<?php echo $this->cdn() ?>/images/website/process_icon.png"></td>
                                            <td><?php if ($parentrequest->status == '0') { ?>
                                                    Pending
                                                <?php } ?></td>
                                            <!--<td><a title="Delete" href="javascript:void(0);"  class="remove-link" onclick="changechildstatus('<?php echo $parentrequest->id ?>', '2', '<?php echo $parentrequest->userid; ?>', 'delete')">Delete</a></td>-->
                                        </tr>

                                        <?php
                                    }
                                    ?>
                                    <!---- -End Request to child ------->
                                    <!--- ---Start Request from child------->
                                                       <?php
                                                    if (count($this->childrequestreceive) != '0') {
                                                        foreach ($this->childrequestreceive as $key => $childrequest) {
                                                            ?>
                                                            <tr>
                                                                <td><?php echo $childrequest->first_name; ?></td>
                                                                <td><a data-toggle="modal" data-target="#userprofile" data-whatever="@mdo" class="showmnu " id="" onclick="getPopupForms('userpopup','<?php echo $childrequest->userid; ?>');" href="#" ><?php echo $childrequest->email_id; ?></a></td>
                                                                  <td><?php if($childrequest->board_name!=''){ echo $childrequest->board_name;}else {?> NA <?php } ?></td>
                                                                <td><?php if($childrequest->class_name){echo $childrequest->class_name;}else{?> NA<?php }?> </td>
                                                                <!--<td  width="15%" align="center"><img width="15" height="15" border="0" src="<?php echo $this->cdn() ?>/images/add.gif"></td>-->
                                                            <td><img width="17" height="17" border="0" src="<?php echo $this->cdn() ?>/images/website/process_icon.png"></td>
                                                                <td align="center"><?php if ($childrequest->status == '0') { ?>
                                                                    <a title="Add" href="javascript:void(0);"  class="remove-link" onclick="changechildstatus('<?php echo $childrequest->id ?>', '1', '<?php echo $childrequest->userid; ?>')">Add</a> / Pending
                                                                    <?php } ?></td>
                                                               
                                                            </tr>
                                                           
                                                            <?php
                                                        }
                                                    }       
                                                    foreach ($this->childData as $key => $child) {
                                                      //echo '<pre>';print_r($child);echo '</pre>';die('Macro');  ?>
                                                        <tr>
                                                            <td id="data-row-<?php echo $key ?>-2"><?php echo $child->first_name; ?></td>
                                                            <td id="data-row-<?php echo $key ?>-3"> <a data-toggle="modal" data-target="#userprofile" data-whatever="@mdo" class="showmnu " id="" title="View Profile" onclick="getPopupForms('userpopup','<?php echo $child->child_id; ?>');" href="#" ><?php if( $child->user_name!=''){echo $child->user_name;}else{
                                                               echo $child->email_id;
                                                            }?></a></td>
                                                            <td id="data-row-<?php echo $key ?>-3"><?php echo $child->board_name; ?></td>
                                                            <td id="data-row-<?php echo $key ?>-3"><?php echo $child->class_name; ?></td>
                                                            <!--<td align="center"><a href="javascript:void(0)" class="showPackageDetails" id="<?php echo $child->child_id; ?>"><img width="15" height="15" border="0" src="<?php echo $this->cdn() ?>/images/add.gif"></a></td>--->
                                                            <td align="center"><a href="<?php echo $this->basePath() ?>/report/index/coverage-report#/coverage/<?php echo $child->child_id; ?>/<?php echo $child->class_id; ?>" title="View your child progress"><img width="17" height="17" border="0" src="<?php echo $this->cdn() ?>/images/website/process_icon.png"></a></td>
                                                            <td>
                                                                
                                                                <?php if($child->relationcount =='0'){
                                                                    ?>
                                                                <a href="<?php echo $this->Url('zfcuser/changepasswordchild',array('userId' => $child->child_id) ); ?>" type="" title="Change password" value="" class=""/>Change Password
                                                                
                                                                <?php }else{?>
                                                                Change Password 
                                                                <?php }?>
                                                                </td>
<!--                                                                 <td>
                                                                
                                                                <?php if($child->relationcount =='0'){?>
                                                                <a href="#" type="" title="Delete" onclick="deletechild(<?php echo $child->child_id;?>,'5','');" value="" class=""/>Delete
                                                                
                                                                <?php }else{?>
                                                                <?php $relation_id = ($child->relationid != '')?$child->relationid:'';  ?>
                                                                <a href="#" type="" title="Delete" onclick="deletechild(<?php echo $child->child_id;?>,'0',<?php echo $relation_id;?>);" value="" class=""/>Delete
                                                                <?php }?>
                                                                </td>-->
                                                        </tr>
                                                        <tr id="PackageDetails_<?php echo $child->child_id ?>" class="details" style="display:none;">
                                                            <td colspan="7">
                                                                <span class="package_close" id ="<?php echo $child->child_id ?>"><img title="Close Details" alt="Close Details" src="<?php echo $this->cdn() ?>/images/x.png"></span>
                                                                <?php if (count($this->childordersDetailes[$child->child_id]) != 0) { ?>

                                                                    <table cellpadding="0" cellspacing="0" width="100%" class="user-sub-table1" style="margin-top:-1px;">
                                                                        <tbody align="left">
                                                                            <tr>
                                                                                <td >Packages</td>
                                                                                <td >Valid from</td>
                                                                                <td >Renewal Due</td>
                                                                                <td >Status</td>
                                                                            </tr>
                                                                            <?php
                                                                            foreach ($this->childordersDetailes[$child->child_id] as $key => $packages) {


                                                                                $validFrom1 = explode(' ', $packages->valid_from);
                                                                                $validFrom = explode(' ', date('F j Y', strtotime($validFrom1[0])));

                                                                                $validTill1 = explode(' ', $packages->valid_till);
                                                                                $validTill = explode(' ', date('F j Y', strtotime($validTill1[0])));
                                                                                $pDate = date('Y-m-d H:i:s');
                                                                                if (strtotime($pDate) > strtotime($packages->valid_till)) {
                                                                                    $status = "Expired";
                                                                                } else {
                                                                                    $status = "Active";
                                                                                }
                                                                                ?>
                                                                                <tr>
                                                                                    <td><?php echo $packages->board . ', ' . $packages->class . ', ' . $packages->package_name ?></td>
                                                                                    <td><?php echo $validFrom[1] . ' ' . $validFrom[0] . ', ' . $validFrom[2]; ?></td>
                                                                                    <td><?php echo $validTill[1] . ' ' . $validTill[0] . ', ' . $validTill[2]; ?></td>
                                                                                    <td><?php if ($status == "Active") { ?>
                                                                                            <span class="status-green">Active</span>
                                                                                        <?php } else { ?>
                                                                                            <span class="status-red">Expired</span>
                                                                                        <?php } ?></td>
                                                                                    <td id="#<?php echo "mobile" . $key ?>" class="view_details"><img onclick="showPopupData('<?php echo $key ?>')" src="<?php echo $this->cdn() ?>/images/view_details.png" width="30px"/></td>
                                                                                </tr>
                                                                            <?php }
                                                                            ?>
                                                                                
                                                                    </table>
                                                                <?php } else { ?>
                                                                    <table width="100%" style="margin-top:-1px;">
                                                                        <tr class="data-row">
                                                                            <td colsapn="6" align="center">You are a trial user, no subscription found.</td>
                                                                        </tr>

                                                                    </table>
                                                                <?php } ?> 
                                                            </td>

                                                        </tr>

                                                    <?php }
                                                    ?>
                                </table>
                                <?php
                            } else {
                                ?>
                                <div class="no-record"><p>No Record.</p></div>

                                <?php
                            }
                            //echo $this->partial('assessment/index/addchildpopup.phtml', array('boardList' => $this->boardList, 'countries' => $this->countries, 'states' => $this->states, 'userCountryId' => $this->userCountryId, 'userStateId' => $this->userStateId, 'userCity' => $this->userCity));
                            ?>
                        </div>
                        </div>
                    </div>
                </section>
                    </div>
            </div>
        </div>
    </div>
 <div class="modal fade addchild-popup userprofile-popup" id="userprofile" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="clearfix"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
        <div class="modal-body" id="model_body">
            
        </div>
        
    </div>
      
  </div>
     
 </div>
 <?php echo $this->partial('user/index/childpopup.phtml', array('boardList' => $this->boardList , 'countries' => $this->countries ,'states' => $this->states ,'userCountryId' => $this->userCountryId , 'userStateId' => $this->userStateId ,'userCity' => $this->userCity)); ?>

<?php }else { ?>
        <script>
            window.location = "<?php echo $this->url('home'); ?>"
        </script>
    <?php } ?>
    <script>

        $(document).ready(function() {
            var tabId = '<?php echo $this->tabview; ?>';
            if (tabId == '1')
            {
                $("#view1").show();
                $("#view2").hide();
                $("#requestsent").addClass('selected');
                $("#requestreceived").removeClass("selected");

            }
            else if (tabId == '2')
            {
                $("#view1").hide();
                $("#view2").show();
                $("#requestsent").removeClass('selected');
                $("#requestreceived").addClass("selected");

            }
        });


        $(document).ready(function() {
            $(".main-bg").height($(".right-content").height() + 7);
        });
        $(window).resize(function() {
            $(".main-bg").height($(".right-content").height() + 7);
        });


        function changechildstatus(Id, Status, childID, type)
        {
            var Id = Id;
            var Status = Status;
            var childID = childID;
            var type = type
            if (Status == '2')
            {
                var conf = confirm('Are you sure you want to delete?');
                if (conf == true) {
                } else {
                    conf = false;
                }
            }
            if (Status == '1')
            {
                var conf = confirm('Are you sure you want to add?');
                if (conf == true) {
                } else {
                    conf = false;
                }
            }

            if (conf == true) {
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->Url('changechildstatus');?>',
                    data: {Id: Id, Status: Status, childID: childID, type: type},
                    success: function(data) {
                        $('#loaddingActivity').hide();
                        if (data['output'] == 'sucusses') {
                            location.reload();
                        }
                    }
                });


            }
        }

        function deletechild(uid, status,relation_id) {

            var conf = confirm('Are you sure you want to delete?');
            if (conf == true) {
                if (uid != '') {
                    $.ajax({
                        type: 'POST',
                        url: '<?php echo $this->Url('deleteparentchild'); ?>',
                        data: {UId: uid, status: status,relationId: relation_id},
                        success: function(data) {
                            if (data['output'] == 'success') {
                                $('#deletemsg').html(data['message']);
                                location.reload();
                            }
                        }
                    });


                }
            }
        }


        $(document).ready(function() {
            $(".main-bg").height($(".right-content").height() + 7);
        });
        $(window).resize(function() {
            $(".main-bg").height($(".right-content").height() + 7);
        });

        $(".showPackageDetails").click(function() {
            var id = $(this).attr("id");
            $(".details").hide();
            $("#PackageDetails_" + id).show();
        });

        $(".package_close").click(function() {
            var id = $(this).attr("id");
            $("#PackageDetails_" + id).hide();
        });


    </script>
    <script type="text/javascript">
        function addChildPopup(str) {
            $("#Login-Social").hide();
            $("#reg_msg").hide();
            $(".log-fld").css({'padding-top': '42px'});
            $("#addChildPopup").show();
            $("#addchild-popup").css("height", "auto");
            $("#ChildDetailPopup").hide();
            $("#childList_box").hide();
            $('#noredirect').css('display', 'block');
            $('#noredirecthere').css('display', 'inline-block');

            $(".addchild-box,.overlay").css('display', 'block');

            $(".overlay").css({'opacity': '0.65'});
        }
        function getPopupForms(type, id) {

            var urlPath = '';
            if (type == 'userpopup') {
                $("#overlay_logins").show();
                $("#login_banner").hide();
                $("#register_banner").hide();
                $("#forgot_banner").hide();
                $('#userprofile').show();
                var userId = id;
                baseURL = '<?php echo $this->url('userprofile'); ?>';
            urlPath = baseURL + '?id=' + userId;

        }
        $.ajax({
            type: 'POST',
            url: urlPath,
            success: function(data) {
                  if (type == 'userpopup') {
                    $('#model_body').html(data);

                   }
            }
        });
    }

</script>  
