<link rel="stylesheet" href="<?php echo $this->basePath("css/website/profile.css"); ?>" type="text/css" media="screen" />
<?php if ($this->zfcUserIdentity()) { ?>
    <div id="content" class="profile-pages">
        <div class="container">
            <div class="row">
                <div class="myprofile-content">
                    <div class="profile-view globle-click clearfix">
                        <strong>My Paper</strong>
                        <i class="icons-ar"></i>	
                    </div>
                    <?php echo $this->partial('user/index/profile-menu.phtml', array('page' => 'mypaper', 'addedmentors' => count($this->addedMentors), 'addedStudents' => count($this->addedStudents))); ?>
                    <section class="profile-block">
                        <input type="hidden" value="nav_5" id="nav_find">
                        <div class="add-member clearfix">
                            <div class="editmentor_button">
                                <a href="<?php echo $this->Url('my-students'); ?>" class="btn btn-primary">Back</a>	
                            </div>	
                        </div>
                        <div class="addChild_Container">
                            <h3>My Students</h3>
                            <div class="mentor-inner">
                                <?php
                                if (count($mentorPaperList) > 0) {
                                    ?>
                                    <table class="table table-bordered">
                                        <tr>
                                            <th width="22%" align="left">Paper</th>
                                            <th width="10%" align="left">Class</th>
                                            <th width="10%" align="left">Subject</th>
                                            <th width="10%" align="left">Student</th>
                                            <th width="10%" align="left">Paper Marks</th>
                                            <th width="10%" align="left">Paper Attempt Status</th>
                                            <th width="10%" align="left">Paper Evaluate Status</th>
                                            <th width="18%" align="left">Action</th>
                                        </tr>
                                        <?php
                                        foreach ($mentorPaperList as $paperList) {
                                            ?>
                                            <tr>
                                                <td align="left"><a href="javascript:void(0);" title="View Paper" onclick="window.open('<?php echo $this->url('viewpaper', array('paperId' => $paperList->paperId)); ?>', 'target=_self', 'fullscreen=yes,location=1,scrollbars=yes')"><?php echo $paperList->paperName; ?></a></td>
                                                <td align="left"><?php echo $paperList->paperClass; ?></td>
                                                <td align="left"><?php echo $paperList->paperSubject; ?></td>
                                                <td align="left"><?php echo $paperList->student_name ?></td>
                                                <td align="left"><?php echo $paperList->paperEvaluatedScore.' / '.$paperList->paperMarks; ?></td>
                                                <td align="left"><?php echo $paperList->paperAttemptStatus; ?></td>
                                                <td align="left"><?php echo $paperList->paperEvaluateStatus; ?></td>
                                                <th align="left">
                                                    <?php
                                                    if ($paperList->paperAttemptStatus == 'no') {
                                                        echo 'Not Yet Attempted';
                                                    } else if ($paperList->paperAttemptStatus == 'yes' && $paperList->paperEvaluateStatus == 'no') {
                                                        ?> <a href="javascript:void(0);" onclick="window.open('<?php echo $this->url('mentortestevaluate', array('paperassignId' => $paperList->paperAssignId,'studentId' => $paperList->paperAssignedTo)); ?>', 'target=_self', 'fullscreen=yes,location=1,scrollbars=yes')"> Evaluate</a> <?php } else if ($paperList->paperAttemptStatus == 'yes' && $paperList->paperEvaluateStatus == 'yes') {
                                                        ?> <a href="javascript:void(0);" onclick="window.open('<?php echo $this->url('testevaluationresult', array('paperassignId' => $paperList->paperAssignId)); ?>', 'target=_self', 'fullscreen=yes,location=1,scrollbars=yes')"> View Results</a> <?php } ?>


                                                </th>
                                            </tr>
                                        <?php } ?>
                                    </table>
                                    <?php
                                } else {
                                    ?>
                                    <div class="no-record"><p>You have not assigned any paper yet.</p></div>
                                    <?php
                                }
                                ?>

                            </div>	
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
<?php } else { ?>
    <script>
        window.location = "<?php echo $this->url('home'); ?>"
    </script>
<?php } ?>
