<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.js" type="text/javascript"></script>
<section class="profile-block">
   <div class="changePassword">
     <form action="" method="post" class="form-horizontal" id="change-pass-form">                  
        <div style="margin-left: 50px">
                       
                    </div>
                    <div class="form-group">
                     <label for="cpass" class="col-sm-4 control-label"><label for="credential">Current Password</label><sup>*</sup></label>
		     <div class="col-sm-8">
		      <input name="credential" id="credential" type="password" class="form-control" value="">                        
		     </div>
                   </div>
                <div class="form-group">
		    <label for="npwsd" class="col-sm-4 control-label"><label for="newpassword">New Password</label><sup>*</sup></label>
		    <div class="col-sm-8">
		     <input name="newpassword" id="newpassword" type="password" class="form-control" value=""></div>
		 </div>
		 <div class="form-group" style="margin-bottom: 0;">
		    <label for="cpswd" class="col-sm-4 control-label"><label for="conformpassword">Confirm Password</label><sup>*</sup></label>
		    <div class="col-sm-8">
		     <input name="conformpassword" id="conformpassword" type="password" class="form-control" value=""></div>
		  </div>
<!--                  <div class="form-group" style="margin-bottom: 0;">
		    <label for="hpass" class="col-sm-4 control-label"><label for="hintpassword">Hint Password</label><sup>*</sup></label>
		    <div class="col-sm-8"><input name="hintpassword" id="hintpassword" type="text" class="form-control" value=""></div>
		  </div>-->
         <div class="form-group" style="margin-bottom: 0;">
		    <label for="vpass" class="col-sm-4 control-label">&nbsp;</label>
		    <div class="col-sm-8">
                  <span class="valid-error" id="ajax_confirmerrormsg" style=""></span>
                        <span class="valid-error greencolor" id="ajax_successmsg" style=""></span>                        
		    </div>
                    </div>
                    
                    <div class="form-group last">
		    <label for="vpass" class="col-sm-4 control-label">&nbsp;</label>
		    <div class="col-sm-8">
                  <input name="submit" type="submit" class="btn btn-primary" id="update-password" value="Update Password">
		    </div>
                    </div>
	    </form>
        </div>
   </section>              

<script>
   // window.alert = function() { }; 
 $.validator.setDefaults({
    submitHandler: function() {
        $("#ajax_confirmerrormsg").hide();
        var credential      = $("#credential").val();
        var newpassword     = $("#newpassword").val();
        var conformpassword = $("#conformpassword").val();
        //var hintpassword    = $("#hintpassword").val();
      $.ajax({
            type: 'POST',
            url: BASE_URL + "/updatepassword",
            dataType: 'json',
            data:{credential:credential,newpassword:newpassword,conformpassword:conformpassword},
            success: function(data) {
               if(data.output=='errorpwd')
               {
                   $("#ajax_confirmerrormsg").show();
                   $("#ajax_confirmerrormsg").html("Current Password does not match our records");
               }else if(data.output=='success'){
                  // alert("Password changed successfully");
                   $('#location10').modal('hide');
                   $('#locationAlert').modal('show');
               }else{
                   $("#ajax_confirmerrormsg").show();
                   $("#ajax_confirmerrormsg").html("There is error while updating your password .Try again !");
               }
               
        }
     });
    }
});

// validate signup form on keyup and submit
$("form").validate({
    rules: {
        credential: {
            required: true
          },
        newpassword: {
            required: true,
            minlength: 6
        },
        conformpassword: {
            required: true,
            minlength: 6,
            equalTo: "#newpassword"
        },
      
    },
    messages: {
        credential: {
            required: "Please provide a password",
        },
        newpassword: {
            required: "Please provide a password",
            minlength: "Your password must be at least 6 characters long"
        },
        conformpassword: {
            required: "Please Confirm  password",
            minlength: "Your password must be at least 6 characters long",
            equalTo: "Please enter the same password as above"
        },
        
    }
});   
    
    
/*$(document).ready(function() {
  $("#update-password").click(function() {
    
        
    });
});*/
</script>
<style>
    .error{ font-size: 12px; font-weight: normal; margin: 0;}    
    .valid-error, .errorfrm_mentor, .errorfrm_mymentor, .error{font-size: 13px;}
</style>