<?php
if (@$childData > 0) {
    foreach ($this->childData as $child) {
        $class_ids = $child->classId;
    }
} else {
    $class_ids = '';
}
?>
<link rel="stylesheet" href="<?php echo $this->basePath("css/website/subreport.css"); ?>" >
<link href="<?php echo $this->basePath("css/website/welcome.css"); ?>" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="<?php echo $this->cdn(); ?>/css/website/report.css" >
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/website/externals/angular.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/container_prog_easypiechart.js"></script>

<script type="text/javascript">
    var siteUrl = '<?php echo $this->basePath(); ?>';
    //alert(siteUrl)
    $(document).ready(function () {
        $(".rightTabaccordion .accord-header").click(function () {
            if ($(this).next("div").is(":visible")) {
                $(this).next("div").slideUp("slow");
            } else {
                $(".rightTabaccordion .accord-content").slideUp("slow");
                $(this).next("div").slideToggle("slow");
            }
        });

        $(".accord-content ul li").click(function () {
            $(".accord-contentli-submenu").toggle("slow");
        });

    });

    var class_id = "<?php if(isset($class_ids)) { echo $class_ids; } ?>";
//if(class_id ==''){
// 
//	$(".preloader").hide();
//	$("#fadded-image").show();
//        
//	}

    $(document).ready(function () {
        $("#board1").change(function () {
            var optionString = '<option value="">Select Class</option>';
            $("#class1").html(optionString);
            if ($(this).val()) {
                $.ajax({
                    type: 'POST',
                    url: BASE_URL + "/lms/index/custom-containerlist/" + $(this).val(),
                    dataType: 'json',
                    success: function (data) {
                        var optionString = '<option value="">Select Class</option>';
                        $("#class1").html(optionString);

                        $.each(data.options, function (key, obj)
                        {
                            optionString += '<option value="' + obj.rack_id + '">' + obj.rack_name + '</option>';

                        }
                        )
                        $("#class1").html(optionString);

                    }
                }
                );
            }

        }
        );
    });
</script>




<!-- Facebook Conversion Code for Extramarks Registration -->
<script>(function () {
        var _fbq = window._fbq || (window._fbq = []);
        if (!_fbq.loaded) {
            var fbds = document.createElement('script');
            fbds.async = true;
            fbds.src = '//connect.facebook.net/en_US/fbds.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(fbds, s);
            _fbq.loaded = true;
        }
    })();
    window._fbq = window._fbq || [];
    window._fbq.push(['track', '6017846005253', {'value': '0.00', 'currency': 'INR'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6017846005253&amp;cd[value]=0.00&amp;cd[currency]=INR&amp;noscript=1" /></noscript>


<div id="content" class="dashboard-content">
    <div class="dashboard-block">
        <div class="container">
            <div class="row">
                <div class="welcome-page">
                    <?php
                    if ($this->welcome) {
                        ?>
                        <div class="welcomcontent">
                            <?php
                            if ($this->usertypeid == 1) {
                                if ($this->boardid == '124') {
                                    $serviceId = 430;
                                } else {
                                    $serviceId = 2756;
                                }
                                ?>                      <?php if ($this->winATab) { ?>
            <?php if (!$this->testGiven) { ?>

                                        <div class="pull-right">
                                            <a class="btn btn-primary" onClick="window.open('<?php echo $this->basePath() . '/lms/mcq/getRegistrationQuizQuestions/' . $this->classid . '/' . $serviceId ?>', 'mywindow', 'width=800,height=600,scrollbars=yes')" href="javascript:void(0);"><strong>Win a Tab</strong></a>
                                        </div>
                                    <?php } ?>
                                <?php }
                            }
                            ?> 
                            <?php
                            if ($this->usertypeid == 1) {
                                //global $freestudent;
                                echo $freestudent;
                            } else if ($this->usertypeid == 2) {
                                if ($this->childcount > 1) {
                                    // echo $this->partial('zfc-user/user/parentpopup.phtml',array('boardList' => $this->boardList , 'countries' => $this->countries ,'states' => $this->states ,'userCountryId' => $this->userCountryId , 'userStateId' => $this->userStateId ,'userCity' => $this->userCity,'userObj'=>$this->userObj));
                                }
                                //global $freeparent;
                                echo $freeparent;
                            } else {
                                //global $freeteacher;
                                echo $freeteacher;
                            }
                            // $_SESSION['user']['first_login'] = ''; 
                            //unset($_SESSION['user']['first_login']);
                            ?>

                        </div>
                    <?php } else { ?>

                        <?php
                        if ($this->usertypeid == 2) {
                            if ($this->childcount < 1) {
                                // echo $this->partial('zfc-user/user/parentpopup.phtml',array('boardList' => $this->boardList , 'countries' => $this->countries ,'states' => $this->states ,'userCountryId' => $this->userCountryId , 'userStateId' => $this->userStateId ,'userCity' => $this->userCity,'userObj'=>$this->userObj));
                            }
                            ?>
                            <!-- parent can show child report from here-->
                            <div style="min-height:350px;">
                                <div class="preloader overallloader" id="preloaderdiv"  style="display: block; top:20%;">
                                    <img src="<?php echo $this->cdn() ?>/images/website/loading_icon.gif" width="50">
                                </div>
                                <div ng-app="multiCoverageApp" style="max-height: 627px; overflow: auto; overflow-x: hidden;">
        <?php if (empty($class_ids)) { ?>
                                        <script>document.getElementById("preloaderdiv").style.display = "none";</script>
                                        <div id="fadded-image" style="display:block;">
                                            <img src="<?php echo $this->cdn() ?>/images/website/faded-progress-img.jpg" style="width:100%;display:block;">
                                        </div>
                                    <?php } else { ?>
                                        <div ng-include="'<?php echo $this->basePath() . '/reportApp/templates/multiCoverageTemplate.html'; ?>'"> </div>
        <?php } ?>
                                </div>
                            </div>

                            <div id="twotables">
                                <div class="schedule-block common-border" id="schedule_dsad">
                                    <div style="display: none;" id="preloader_schedule" class="preloader">

                                        <img width="50" ng-src="<?php echo $this->cdn() ?>/images/loading_icon.gif" src="<?php echo $this->cdn() ?>/images/website/loading_icon.gif">

                                    </div>
                                    <div class="con-grp-box">
                                        <h2>My package &frasl; Buy package</h2>
                                        <div class="schedule-graphs">
                                            <ul style="margin:10px 10px 0; padding:0px;">
                                                    <?php if (count($this->parentpkg) > 0) { ?>  
                                                        <?php foreach ($this->parentpkg as $key => $packages) { ?>  
                                                        <li >
                                                                <?php echo $key + 1; ?>. <a href="<?php echo $this->URL('my-subscriptions'); ?>" style="font-size:14px !important; color:#272959; font-family:Arial, Helvetica, sans-serif;"><?php echo $packages->board . ',(' . $packages->class . '),' . $packages->package_name; ?> </a>
                                                            <span id="subwidget"><strong class="userSubject">Subject</strong> <?php
                                                                $key = $packages->actual_package_id;
                                                                $key1 = $packages->package_syllabi_id;
                                                                echo $this->SubjectdataWidget($key, 'subscription', $key1);
                                                                ?></span>
                                                        </li>
                                                        <?php
                                                    }
                                                } else {
                                                    ?>
                                                    <a href="<?php echo $this->URL('package'); ?>" style="font-size:14px !important; color:#272959; font-family:Arial, Helvetica, sans-serif;">Buy package </a>
        <?php } ?>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <!--<div ng-click="mcqTestEligiblity(userType);" ng-class="senior"  class="performance-block common-border">
                                     <div style="display: none;" id="preloader_test" class="preloader">
                                         <img width="50" ng-src="/emsite/public/images/website/loading_icon.gif" src="/emsite/public/images/website/loading_icon.gif">
                                     </div>
                                     <div class="con-grp-box">
                                         <h2>Parents corner</h2>
                                         <div class="schedule-graphs">
                                             <ul style="margin:10px 10px 0; padding:0px;">
                                                 <li style="font-size:14px !important; color:#272959; font-family:Arial, Helvetica, sans-serif;">
                                                     1. consolidate feedback
                                                 </li>
                                                 <li style="font-size:14px !important; color:#272959; font-family:Arial, Helvetica, sans-serif;">
                                                     2. exam notification
                                                 </li>
                                             </ul>  
                                         </div>
                                     </div>
                                 </div>-->
                                <!--<div ng-click="mcqTestEligiblity(userType);" ng-class="senior"  class="performance-block common-border">
                                    <div style="display: none;" id="preloader_test" class="preloader">
                                        <img width="50" ng-src="<?php echo $this->basePath(); ?>/images/website/loading_icon.gif" src="<?php echo $this->basePath(); ?>/images/website/loading_icon.gif">
                                    </div>
                                    <div class="con-grp-box">
                                        <h2>Childs Activities</h2>
                                        <div class="schedule-graphs">
                                            <input type='radio' name='child_activities' value='overall_feedbacks'/>
                                            Overall Feedbacks
                                            
                                            <input type='radio' name='child_activities' value='tests'/>
                                            Tests
                                            
                                            <input type='radio' name='child_activities' value='child_query_to_mentor'/>
                                            Child's query to mentor
                                            
                                            <select name="child">
                                                <option value="">Select Child</option>
                                            </select>
                                            <select name="subject">
                                                <option value="">Select Subject</option>
                                            </select>
                                            <input type='button' name='Go' value='Go'/>
                                        </div>
                                    </div>
                                </div>-->
                            </div>      
                            <!--                               <li>
                                                              
                            <?php
                            if (count($childData) > '0') {
                                foreach ($childData as $child) {
                                    ?>
                                                                                                       <a href="<?php //echo $this->basePath()     ?>/report/index/coverage-report#coverage/<?php echo $child->user_id; ?>/<?php echo $child->classId; ?>" title="View your child progress"><img src="<?php echo $this->cdn() ?>/images/add-child_white.png"> <span>View your child progress</span></a>
                                                                                                   
                                    <?php
                                    break;
                                }
                            } else {
                                ?>
                                                                                   <a href="<?php //echo $this->URL('myChild');   ?>" onclick="addChildPopup(''); return false;"><img src="<?php echo $this->cdn() ?>/images/add-child_white.png"> <span>Add a child</span></a>
                            <?php } ?>
                                                          </li>  -->

                        <?php } else { ?>
                                        <!--                          <li><a href="<?php //echo $this->URL('my-students');  ?>"><img src="<?php echo $this->cdn() ?>/images/add-child_white.png"> <span>Add Learner</span></a></li>-->
                            <?php } ?>
                        <ul class="parent_section-ul">
    <?php if ($this->usertypeid == 3) { ?> 

                                <li><a href="<?php echo $this->URL('my-students'); ?>"><img src="<?php echo $this->cdn() ?>/images/website/add-child_white.png"> <span>Add Learner</span></a></li>
                                <li><a  onclick="menuHidden();" href="javascript:void(0);" data-toggle="dropdown" style="outline: medium none;" id="indian_boards" class="dropdown-toggle closes"><img src="<?php echo $this->cdn() ?>/images/website/Start-as-learner-icon.png"><span>Start As a Learner</span></a></li>

                            <?php } else { ?>		 
                                        <!--               <li><a onclick="menuHide();" href="javascript:void(0);" data-toggle="dropdown" style="outline: medium none;" id="indian_boards" class="dropdown-toggle closes"><img src="<?php //echo $this->basePath()    ?>/images/Start-as-learner-icon.png"><span>Start As a Learner</span></a></li>-->
                        <?php } ?>

                        </ul> 
<?php } ?>

                </div>

                <div class="profileNotification custom-tooltip">
<?php echo $this->NotificationWidget(); ?>
<?php echo $this->RightPanelWidget((isset($_SESSION['user']['user_type_role'])) ? $_SESSION['user']['user_type_role'] : '', $this->navigationarray, $this->satPackage, $this->capPackage); ?>
                </div>
            </div>
        </div>

    </div>
</div>
<?php
if (isset($_SESSION['customBoarddetail']['customboardId'])) {
    $sessCustomBoardId = $_SESSION['customBoarddetail']['customboardId'];
} else {
    $sessCustomBoardId = '';
}
$userType = '';
if ($user = $this->zfcUserIdentity()) {
    $userName = $user->getDisplayName();
    $userMale = $user->getGender();
    $userType = $user->getUserTypeId();
    $userphoto = $user->getuserPhoto();
}
$userTypeSession = $userType;
if (isset($_SESSION['user_role']) && $_SESSION['user_role'] != '') {
    $userTypeSession = $_SESSION['user_role'];
}
//echo $userTypeSession; exit;
?>
<?php if ($userTypeSession == 1 && (!$this->classid || !$this->isClass)) { ?>
    <!---   start popup --->
    <!--div class="dashboard_overlay"></div>   
    <div class="modal addchild-popup" id="loginDetails" style="display:block;" class="nursery-box sign-box" id="nursery-popup">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">Select your Board and Class below</h4>
                </div>
                <div class="modal-body">
                    <form name="nursery" id="nursery" method="post" class="form-horizontal">
                        <div class="prefer" id="boardclass_box" style="display: block; padding-top: 5px;">
                            <div class="form-group">
                                <div class="board-box col-sm-6">
                                    <select name="board1" id="board1" tabindex="1" class="form-control boardClass">
                                        <option value="">Select Board</option>
                                        <?//php foreach ($boardList as $key => $value) { ?>
                                            <option value="<?//php echo $key; ?>"><?//php echo $value; ?></option>
                                        <?//php } ?>
                                        <?/*php
                                        foreach ($boardList as $key => $val) {
                                            if ($val == 'ICSE') {
                                                /*?>
                                                <option value="<?//php echo $key; ?>">Other</option>
                                                <?/*php
                                            }
                                        }*/
                                        ?>
                                    </select>
                                    <div class="clear"></div>
                                    <span id="errormessageBoard" style="color:red;padding:5px 0 5px 0px;"></span>
                                </div>
                                <div class="class-box form-group col-sm-6" id="classdetails1">
                                    <div id="selectClass">
                                        <select name="class1" id="class1" class="form-control"  tabindex="2" style="position:inherit;">
                                            <option value="">Select Class</option>
                                        </select>
                                    </div>
                                    <div class="clear"></div>
                                    <span id="errormessageClass" style="color:red;padding:5px 0 5px 0px;"></span>
                                </div>
                            </div>
                        </div>  
                        <div class="register_conf_button">
                            <div class="log-bx" id="otherboardclass" style="display:none;padding-left:10px;">
                                <div class="log-rhtbx" style="width:45%">
                                    <input id="otherboard" class="inputBg" type="text" style="padding:3px 5px" name="otherboard" tabindex="13">
                                    <div class="clear"></div>
                                    <span style="color:red;padding:5px 0;font-size: 14px;" id="errorotherboard"></span>
                                </div>
                            </div>
                            <div class="register_submit_board form-group" id="submit_button" style="display: block;">
                                <a class="register" id="various1" style="margin-right:3%; float:right;" onclick="return updateBoardClassParent('<?php echo $_SERVER['HTTP_HOST'] ?>')" href="javascript:void(0);" tabindex="3"> <div class="logins btn btn-warning">SUBMIT</div></a>
                            </div>
                        </div>	
                        <span id="loadding" style="display:none"><img src="<?php echo $this->cdn() ?>/images/website/loader16.gif"/></span>
                        <div id="regSuccessful"></div>			
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!---end popup---->
<?php }?>
<script>

    <?php if($this->testGiven){ ?>
            alert('Thank You For Giving The Test!!');
<?php } ?>

        function menuHidden() {
            if ($(".dropdown-menu").css('display') == 'block') {
                $(".dropdown-menu").hide();
                $(".blank_div").hide();
                var data = {
                    userrole: 0
                }
                changeUserRole(data);

            } else {
                $(".dropdown-menu").show().addClass("highlight_zindex");
                $(".blank_div").show().removeClass("highlight_zindex");
                var data = {
                    userrole: 1
                }
                changeUserRole(data);
            }
        }


        function changeUserRole(data) {
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->basePath(); ?>/user/changeuserrole',
                data: data,
                dataType: 'html',
                async: false,
            success: function(data) {//alert(data.key)
                    location.href = "<?php echo $this->Url('zfcuser/user-dashboard'); ?>/" + data;
                    return true;
                }
            });
        }

</script>
<script>
    $(window).load(function() {

       //$('#location11').modal('show');
                });
</script>

<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/website/externals/angular-route.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/website/externals/angular-sanitize.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/website/externals/underscore-min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/container_prog_easypiechart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/container_prog_carousel.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/container_prog_easypiechart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/website/owl.carousel.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/container_prog_easySlider1.7.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/reportApp/js/controllers/multiCoverageController.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/reportApp/js/services/filter.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/website/externals/package.js"></script>
