<footer>
    <div class="container">
        <div class="row">
            <div class="clearfix">
               	
                    <div class="col-xs-2 footer-list">
                        <h3>Extramarks</h3>
                        <ul>
                            <li><a href="<?php echo $this->url('aboutus') ?>">About us</a></li>
                            <li><a href="<?php echo $this->url('about-leader') ?>">Leadership</a></li>
                            <li><a href="<?php echo $this->url('awards') ?>">Awards</a></li>
                            <li><a href="http://www.extramarks.com/newsletter/2014/sep-dec/index.html" target="_blank">Newsletters</a></li>
                        </ul>
                    </div>	
                    <div class="col-xs-4 footer-list">
                        <h3>Product &amp; Services</h3>
                        <ul>
                            <li><a href="<?php echo $this->Url('school-solutions') ?>" title="School Sulutions">School Solutions</a></li>
							<li><a href="<?php echo $this->url('extramarks-live-tab') ?>" title="Extramarks Live Tab">Extramarks Live Tab</a></li>
							<li><a href="<?php echo $this->url('studyabroad') ?>" title="Study Abroad Services">Overseas Study</a></li>
							<li><a href="<?php echo $this->url('caphome') ?>" title="Career &amp; Assessment Program">Career Assessment Program</a></li> 
							<li><a href="http://eprakhar.com" target="_blank" title="Skill Development">Skill Development</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-2 footer-list">
                        <h3>Testimonials</h3>
                        <ul>
                            <li><a href="<?php echo $this->url('students') ?>">Students</a></li>
                            <li><a href="<?php echo $this->url('parents') ?>">Parents</a></li>
                            <li><a href="<?php echo $this->url('teachers') ?>">Teachers</a></li>
                            <li><a href="<?php echo $this->url('school') ?>">School</a></li>
                        </ul>
                    </div>
                
                
                    <div class="col-xs-2 footer-list">
                        <h3><a href="<?php echo $this->url('terms-of-use') ?>">Legal</a></h3>
                        <ul>
                            <li><a href="<?php echo $this->url('terms-of-use') ?>">Terms of Use</a></li>
                            <li><a href="<?php echo $this->url('user-policy') ?>">User Policy</a></li>
                            <li><a href="<?php echo $this->url('copyright-policy') ?>">Copyright</a></li>
                            <li><a href="<?php echo $this->url('report-abuse') ?>">Report Abuse</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-2 footer-list">
                        <h3><a href="<?php echo $this->url('faq') ?>">FAQ</a></h3>
                        <ul>
                            <li><a href="<?php echo $this->url('child-safety') ?>">Child Safety</a></li>
                            <li><a href="<?php echo $this->url('privacy') ?>">Privacy</a></li>
                            <li><a href="<?php echo $this->url('disclaimer') ?>">Disclaimer</a></li>
                        </ul>
                    </div>
                
            </div>
            <div class="footer-bottom">
                <ul>
                    <li><a href="<?php echo $this->url('contact-us') ?>">Contact</a> | </li>
                    <li><a href="<?php echo $this->url('careers') ?>">Careers</a> | </li>
                    <li><a href="<?php echo $this->url('sitemap') ?>">Sitemap</a> | </li>
                    <li><a href="/rss.xml">RSS Feed</a></li>	
                </ul>
                <p class="copyright">Copyright(c) 2014 Extramarks. All rights reserved. </p>	
            </div>	
        </div>	
    </div>
</footer>
<script>
document.oncontextmenu=disableit
function disableit()
{
//alert("done")
return false;
}
</script>
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//v2.zopim.com/?2NlZ9lrv9aGdB2Rb9uVIhKDwQX1tvO3n';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
