<section class="search-container container">
    <div class="col-md-6 col-md-offset-3">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for location">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go</button>
            </span>
        </div>
    </div>
</section>
<div id="fullpage">
    <div class="section things-around-me container-fluid" data-anchor="things-around-me" >
        <div class="col-md-6 col-md-offset-3 text-center" style="height:200px;">
            <i class="glyphicon glyphicon-check white big-icon" style="margin-bottom:20px"></i>
            <span class="white label-section" style="display:block;">Things Around Me</span>
        </div>
    </div>
    <div class="section women-section container-fluid" data-anchor="women" >
        <div class="col-md-6 col-md-offset-3 text-center" style="height:200px;">
            <i class="glyphicon glyphicon-user white big-icon" style="margin-bottom:20px"></i>
            <span class="white label-section" style="display:block;">Women</span>
        </div>
    </div>
    <div class="section men-section container-fluid" data-anchor="men" >
        <div class="col-md-6 col-md-offset-3 text-center" style="height:200px;">
            <i class="glyphicon glyphicon-user white big-icon" style="margin-bottom:20px"></i>
            <span class="white label-section" style="display:block;">Men</span>
        </div>
    </div>
</div>